### ISSUE TITLE
Tinkerbell Docs Updates

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tink#103]
- [ ] We need to include what the docs assume we have running already, namely Terraform and Docker

- [ ] Note what the `project id` is (hash after projects in the url) on this [page](https://tinkerbell.org/setup/packet/)

- [ ] Set an expectation on provisioning. It took nearly 6 minutes and we didn't know if everything was moving as expected. (Will be nice to write: “it takes average 5minutes”)

- [ ] What comes after Tinkerbell is provisioned? Now that Tinkerbell was provisioned and everything is working, what happens next? You have to press the arrow at the left to know what you have to do, but it is nice to write it at the end of the page.

- [ ] When you run the setup script it asks for:
Following network interfaces found on the system:
eno1
eno2
enp1s0f0
enp1s0f1
Which one would you like to use for with Tinkerbell? As side note, @gianarb picked a wrong one and now I don’t know how to change it, so I did terraform apply again. (Answer looks to be enp1s0f1)

- [ ] The `SSH into the provisioner for the following steps:` is easy to over look. Could we make that bold?

- [ ] We need to include troubleshooting for the “Error: The facility sjc1 has no provisionable c3.small.x86 servers matching your criteria.” You have to change the target datacenter in `main.tf`. You'll need to change it in three places for the vlan and both machines. 

If you see “Error: The facility sjc1 has no provisionable c3.small.x86 servers matching your criteria” you can change the target datacenter in main.tf (You need to change it in 3 places, the vlan, and both machines) It would be great if we had a CLI command or endpoint we could query to find out about availability.

Mark couldn’t find any c3.small.x86 in ams1, ewr1, nrt1, or sjc1. Switch to c1.small.x86 in Amsterdam and it wouldn't work. The docs should specify it has to be c3.small.x86 for Tinkerbell to work.

**Comment by gianarb** [comment]
I had a chat with Thom, and this is out of date and can be closed
