### ISSUE TITLE
Unable to install vim on the provisioner.

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tink#104]
We weren't able to install vim and had to run everything in vi. Other basic linux functions like `yum` weren't available.

**Comment by parauliya** [comment]
@thomcrowe , As I am not quite getting the issue, Could you please explain what you tried and at which steps you faced this issue?

**Comment by mrmrcoleman** [comment]
I think this is a T-Bell issue @gauravgahlot . The Packet Ubuntu machine didn't have Vim and apt-get didn't work for some reason.

I'll let @thomcrowe confirm.

**Comment by gauravgahlot** [comment]
@mrmrcoleman I'm not quite sure. I set up a provisioner a few minutes ago and could install `vim` with `apt-get` without a problem. So, we could really use some details from @thomcrowe.

**Comment by grahamc** [comment]
Hey @thomcrowe, it looks ilke you were expecting the host to be centos or another redhat derivative. In this case, though, the machine is ubuntu and uses `apt` / `apt-get` for installing packages.

**Comment by mrmrcoleman** [comment]
@grahamc This is probably my fault. I meant to say yum, not apt-get.

We couldn't find any package manager on the machine.

**Comment by grahamc** [comment]
At any rate, I wonder if you can reproduce it today? If so, it might be useful to get on a call and do a show-and-tell of the problem.

**Comment by mrmrcoleman** [comment]
Agreed. @thomcrowe Can you see if you can reproduce?

**Comment by thomcrowe** [comment]
Let me give it a try this afternoon.
