### ISSUE TITLE
Errors when spinning up the provisioner and worker

### ISSUE THREAD

**Issue by thomcrowe** [tinkerbell/tink#105]
When the datacenter didn’t have hosts for both provisioner and worker, it spent over 3 minutes creating the provisioner before failing; the worker wasn’t started. After it failed, the provisioner was still there until I ran terraform apply with the new datacenter details.

It would be great if we had a CLI command or endpoint we could query to find out about availability.

Mark couldn’t find any c3.small.x86 in ams1, ewr1, nrt1, or sjc1 and only knew there was an issue after trying to spin up. 

Does Tinkerbell have to run on  c3.small.x86? When Mark tried to switch to c1.small.x86 in Amsterdam and it worked. Then it broke with:

> `Error: POST https://api.packet.net/ports/ac8144a2-5656-47a2-a954-30b61dafd10e/disbond: 422 This device is not enabled for Layer 2. Please contact support for more details.`

  > `on main.tf line 19, in resource "packet_device" "tf-provisioner":
  19: resource "packet_device" "tf-provisioner" {`

> `Error: POST https://api.packet.net/ports/fd9e24e7-0c63-4b90-a2f4-218447a6d8b7/disbond: 422 Hardware invalid server type` 

  > `on main.tf line 30, in resource "packet_device" "tf-worker":
  30: resource "packet_device" "tf-worker" {`

He tried again with a c3.small.x86 for the worker.

> `Error: POST https://api.packet.net/ports/c0eea99b-7d89-40f5-bcc7-c6dee46f226f/disbond: 422 This device is not enabled for Layer 2. Please contact support for more details.`

  > `on main.tf line 19, in resource "packet_device" "tf-provisioner":
  19: resource "packet_device" "tf-provisioner" {`

**Comment by parauliya** [comment]
@thomcrowe , I think these are generally happen a few times when Packet provider failed to create devices or failed to convert a device in Layer2. So this issue is somewhat related to Packet internals while creating a machine.
@mrmrcoleman , Could you please suggest a right person to asssign this issue from the Packet team?

**Comment by mrmrcoleman** [comment]
Two issues:

1. Cannot find c1.small.x86 even though it is available through the API <-- Are these still listed through the capacity end point?
2. Users should be able to find out which machines support Layer 2 before trying to provision. <-- Can we find this our from an API call if not via the website?
3. Update the Tinkerbell setup guide to explain this.
4. When selected All generations of All machines on the website, we are only presented with a small group of machines.

**Comment by gianarb** [comment]
@mrmrcoleman  the image is listed in the available one from the packet-api:

```
$ packet-cli plan get
+--------------------------------------+---------------+---------------+
|                  ID                  |     SLUG      |     NAME      |
+--------------------------------------+---------------+---------------+
| d16a68ff-b21c-4781-a22b-3a0f37c435f8 | c2.large.arm  | c2.large.arm  |
| 5aeee4f9-1137-4514-8f3e-a1e103b02966 | c2.medium.x86 | c2.medium.x86 |
| 359ba4aa-6353-4480-bce2-a6dcd5a69aaa | c3.medium.x86 | c3.medium.x86 |
| 18e285e0-1872-11ea-8d71-362b9e155667 | c3.small.x86  | c3.small.x86  |
| 18810cec-1711-4f30-b323-a1001804b10f | g2.large.x86  | g2.large.x86  |
| c5a9c64a-07e4-46a9-8dfe-2437f521dcb8 | m2.xlarge.x86 | m2.xlarge.x86 |
| 174c4bec-7090-4651-9b81-567080a4a7cb | n2.xlarge.x86 | n2.xlarge.x86 |
| e645c9a0-2156-47e7-b42e-39d0ccb52022 | s3.xlarge.x86 | s3.xlarge.x86 |
| 87728148-3155-4992-a730-8d1e6aca8a32 | storage_1     | Standard      |
| d6570cfb-38fa-4467-92b3-e45d059bb249 | storage_2     | Performance   |
| c3ee2482-060c-4d17-949f-377ee3c18b08 | x2.xlarge.x86 | x2.xlarge.x86 |
| 3bc8a214-b807-4058-ad4a-6925f2411155 | baremetal_2a  | c1.large.arm  |
| 6d1f1ffa-7912-4b78-b50d-88cc7c8ab40f | baremetal_1   | c1.small.x86  |
| 741f3afb-bb2f-4694-93a0-fcbad7cd5e78 | baremetal_3   | c1.xlarge.x86 |
| a3729923-fdc4-4e85-a972-aafbad3695db | baremetal_2   | m1.xlarge.x86 |
| 66173669-84fc-43b3-92b5-64f84497c887 | baremetal_s   | s1.large.x86  |
| e69c0169-4726-46ea-98f1-939c9e8a3607 | baremetal_0   | t1.small.x86  |
| e829e15f-bfa0-4d8f-806e-cc92bb6567b4 | baremetal_1e  | x1.small.x86  |
+--------------------------------------+---------------+---------------+
```

The capacity call does not return them:

```
$ packet-cli capacity get | grep c1.small
```

**Comment by mrmrcoleman** [comment]
The list of non-Layer 2 enable machines is listed here: https://www.packet.com/developers/docs/network/advanced/layer-2/

**Comment by gianarb** [comment]
So, in order to stay provider agnostic where should we place this information to? In the Getting Started we mention Packet, probably we can leave the link there, it looks like one of the things that users should know but that is not obvious at all and sad when it happens because you don't know how to solve it

**Comment by gianarb** [comment]
I think most of those points are not addressed! I remember when we opened it back in the day, Saturday trying to make Tinkerbell to work!
