### ISSUE TITLE
tink hardware doesn't have delete action

### ISSUE THREAD

**Issue by wangxin311** [tinkerbell/tink#109]
tink hardware command doesn't have delete action compare to other tink commands, I know we can push empty json body to get the "delete" result, but it would be nice to have "delete" action.
```
Examples:
tink hardware [command]

Available Commands:
  all         Get all known hardware for facility
  id          Get hardware by id
  ingest      Trigger tinkerbell to ingest
  ip          Get hardware by any associated ip
  mac         Get hardware by any associated mac
  push        Push new hardware to tinkerbell
  watch       Register to watch an id for any changes
```

**Comment by gauravgahlot** [comment]
@parauliya Please link the RFC in the discussion.

**Comment by parauliya** [comment]
Following is the link of RFC for this issue:
https://github.com/tinkerbell/tink/wiki/RFC-%234--Adding-the-functionlity-of-deleteing-the-hardware
