### ISSUE TITLE
The terms in the hello-world docs need to be explained better

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#120]
[When reading the hello-world docs](
https://github.com/tinkerbell/tink/blob/master/docs/hello-world.md) (a link is shown from setup.sh at the end) - there are a few confusing references that could be explained better for new users.

## 1) Unexplained literal value in example

`$ tink workflow create -t <template-uuid> -r ‘{“device_1”:“mac/IP”}’` <- is that the literal value, or does this need elaborating to say that you can replace it with the MAC or IP?

<img width="919" alt="Screenshot 2020-05-18 at 13 35 19" src="https://user-images.githubusercontent.com/6358735/82213899-d1fe9080-990c-11ea-9293-ddec1e29910d.png">

## 2) No context given on what the hardware UUID is or how it's meant to be generated 
```
A few details to note:
* id is the hardware UUID
```

With the `id` - there is no explanation on what this is supposed to be used for. Is it just meant to be a randomly generated UUID with no relationship to anything? If so, why not provide that information to the user and a command to generate a uuid? i.e. `uuid | tr "[:upper:]" "[:lower:]"`

## 3) Is the link at the end of setup.sh still correct?

Also, should this be linking to somewhere on https://tinkerbell.org or to the docs here on GitHub?

We also have a rouge `\n` which should be removed

<img width="1472" alt="Screenshot 2020-05-18 at 13 44 05" src="https://user-images.githubusercontent.com/6358735/82214395-acbe5200-990d-11ea-9f67-50d98d494032.png">

## 4) What does `device_1` mean?

Initial impressions - is `device_1` a magic or hard-coded reference? I can't see it mentioned anywhere in the blog post.

Potential solution, quote the template in the post, so that people can see that `device_1` will be injected:

```
version: '0.1'
name: hello_world_workflow
global_timeout: 600
tasks:
- name: "hello world"
  worker: "{{.device_1}}"
  actions:
  - name: "hello_world"
    image: hello-world
    timeout: 60
```

At the same time, you could explain what the workflow does

https://github.com/tinkerbell/tink/blob/master/docs/examples/hello-world.tmpl

**Comment by gauravgahlot** [comment]
@alexellis I believe this can be closed now. Could you please verify?

**Comment by alexellis** [comment]
Which PRs fixed this? Can you link me to them so that I can verify it?

**Comment by gauravgahlot** [comment]
Related PRs:
 - https://github.com/tinkerbell/tink/pull/123
 - https://github.com/tinkerbell/tinkerbell.org/pull/48
 - https://github.com/tinkerbell/tinkerbell.org/pull/63
 - https://github.com/tinkerbell/tinkerbell.org/pull/44

**Comment by parauliya** [comment]
@alexellis , The links are provided by @gauravgahlot fixed the same. You can go through them. 
But most importantly, the link which was provided at the end of `setup.sh` has changed now. So you should go to the new link for the Hello world example (https://tinkerbell.org/examples/hello-world/) and see if everything is explained there are well descripted.

**Comment by gianarb** [comment]
Thanks Alex!
@DailyAlice updated the example and I think it is not 100 times better! if you have any suggestions feel free to open a PR!
