### ISSUE TITLE
worker machine can only pick up worker_id on the top (1st created)

### ISSUE THREAD

**Issue by yetang-equinix** [tinkerbell/tink#125]
When i have multiple hardware pushed.
##### on provisioner: ####################
/tmp # tink hardware all
{"id": "936d419d-1dc5-4dcd-a938-15ef8bf6970f", ....................{"mac": "50:6b:4b:b7:14:36"}}
{"id": "daea02ec-24b9-4e7a-834b-a306bc4ea49f",................... {"mac": "98:03:9b:89:cf:2e"}}
{"id": .............................}

######### on worker machine: ################
and when worker machine do pxe boot, it always pick up the first hardware, even the mac does not match its own mac:
INFO[0000] All workflows finished                        worker_id=936d419d-1dc5-4dcd-a938-15ef8bf6970f
localhost:/# ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 98:03:9B:89:CF:2E

**Comment by parauliya** [comment]
@yetang-equinix , Could you please look at the output of command `tink workflow list` and check if there is any workflow for the current mac address? 
Also please post the output here in the bug so that I can also have a look.

**Comment by yetang-equinix** [comment]
I don't have the setup anymore. i did have workflow created for both MACs.

**Comment by parauliya** [comment]
@yetang-equinix , Have you tried after that with multiple hardware anymore?

**Comment by parauliya** [comment]
@yetang-equinix 
I tried the same thing at my end as follows:
1. Pushing two hardware data
2. Creating two workflow one for each hardware
3. Reboot both hardware machines one by one.

Results:
Both the workflows completed successfully.

Following is the output of respective command:
1. Command : `tink workflow list`  
  ```
 +--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
| WORKFLOW ID                          | TEMPLATE ID                          | HARDWARE DEVICE                   | CREATED AT                    | UPDATED AT                    |
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
| 06fb4d2e-7ba4-4dcd-b813-cad7a5db197d | 81b29f5a-b361-4a33-b670-1fb5baaf3540 | {"device_1": "98:03:9b:ca:a6:ec"} | 2020-05-28 09:10:15 +0000 UTC | 2020-05-28 09:10:15 +0000 UTC |
| c6c950bc-04cc-44b4-b713-3bcb5889be7b | 0e87085e-9536-40a2-99ab-04923eb3f052 | {"device_2": "98:03:9b:89:da:ae"} | 2020-05-28 09:20:50 +0000 UTC | 2020-05-28 09:20:50 +0000 UTC |
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
```
2. Command : `tink workflow state 06fb4d2e-7ba4-4dcd-b813-cad7a5db197d`
```
+----------------------+--------------------------------------+
| FIELD NAME           | VALUES                               |
+----------------------+--------------------------------------+
| Workflow ID          | 06fb4d2e-7ba4-4dcd-b813-cad7a5db197d |
| Workflow Progress    | 100%                                 |
| Current Task         | OS Installation                      |
| Current Action       | server_partitioning                  |
| Current Worker       | f91db45b-fc1f-4c09-97bf-89433995ca0e |
| Current Action State | ACTION_SUCCESS                       |
+----------------------+--------------------------------------+
```
3. Command : `tink workflow state c6c950bc-04cc-44b4-b713-3bcb5889be7b`
```
+----------------------+--------------------------------------+
| FIELD NAME           | VALUES                               |
+----------------------+--------------------------------------+
| Workflow ID          | c6c950bc-04cc-44b4-b713-3bcb5889be7b |
| Workflow Progress    | 100%                                 |
| Current Task         | OS Installation                      |
| Current Action       | server_partitioning                  |
| Current Worker       | 183650ae-ed69-4723-8e1f-7e13f5fd1ce4 |
| Current Action State | ACTION_SUCCESS                       |
+----------------------+--------------------------------------+
```

Since things are working as expected at my end I am closing this issue. If you face this issue again in future you can reopen it at that time.
