### ISSUE TITLE
setup.sh: configure the network using netplan in Ubuntu 18.04+

### ISSUE THREAD

**Issue by rgl** [tinkerbell/tink#129]
[setup.sh](https://github.com/tinkerbell/tink/blob/527cd4267ae6c0393e8dd725834eca30aaed367d/setup.sh) assumes that all Ubuntu versions use the `/etc/network/interfaces` file to configure the network interfaces, but since Ubuntu 18.04 they no longer use that file neither the ifup/ifdown commands to manage the network interfaces; as such, the following code should be modified to support netplan:

https://github.com/tinkerbell/tink/blob/527cd4267ae6c0393e8dd725834eca30aaed367d/setup.sh#L234-L256

Are you willing to accept a PR to configure netplan in Ubuntu 18.04 and above?

**Comment by rgl** [comment]
BTW, as a workaround, if we pre-configure the interface with the main ip address and the nginx ip address, we can install without problem.

**Comment by gauravgahlot** [comment]
@rgl A PR is always welcome. :100:
