### ISSUE TITLE
Action Images Don't Compose Well (M*N -> M+N)

### ISSUE THREAD

**Issue by grahamc** [tinkerbell/tink#138]
Action Images have a potential to simplify the provisioning process for distributions by creating clear "checkpoints" between phases. However, they don't do that yet.

You can see the intent to compose trying to escape in the various workflows people have made:

```
workflow/01-wipe-disk
workflow/02-install-os
workflow/03-configure-os
workflow/04-install-k8s
workflow/05-reboot
```

```
ubuntu/01-disk-wipe
ubuntu/02-disk-partition
ubuntu/03-install-root-fs
ubuntu/04-install-grub
ubuntu/05-post-install
ubuntu/06-cleanup
```

I thought it would be interested to look at the `disk-wipe` vs. `wipe-disk` phases, and you can see somebody has learned some lessons in one vs the other: one did a fairly naive erase, the other handled mdraid, efibootmgr, among other things.

The composition, however, is too powerful to ignore. Imagine a marketplace of action images:

- wipe disks 
- partition and mount disks based on some json document
- a basic installer for (centos,debian,nixos,alpine)
- a bunch of images to add and run some software like run chef-solo, or cloud-init, etc.
or more, like registering the 

Being able to build and maintain each of these individually means people don't have to learn the ins and outs of disk formatting, and operating systems don't need to learn the details of all the systems.

Ideally, the outcome of this is taking provisioning bare metal from something like (types of hardware) * (operating systems) to more of a (types of hardware) + (operating systems) problem. Check out https://langserver.org/ for an example of how powerful this idea can be. Let's help people pull off-the-shelf action images and get to working deployments quickly.

---

One way Action Images don't compose well, specifically is mounts. Any ActionImage which needs to touch the mounted filesystems has to re-mount everything. This is due to the mount namespace of docker containers forcing all the mounted filesystems to unmount at the end of its run. I'm not sure of a fix here, beyond maybe having a convention of the `partition` image exporting a `fstab` which is mounted just with `mount -a`.

**Comment by alexellis** [comment]
Reminds me of what I wanted to see from: #91
