### ISSUE TITLE
How to deploy a Windows server using PXE on the Worker VM.

### ISSUE THREAD

**Issue by iyamagata** [tinkerbell/tink#142]
I want to deploy a Windows server using PXE on the Worker VM.
Please let me know how to push a Windows image to the Provisioner.

**Comment by nwmcsween** [comment]
1. sysprep an image which will give you a wim file, use an unattened.xml as well so windows auto installs without messing
around
2. format and partition with ntfs
3. use https://wimlib.net/ in the workflow to apply the wim image to the formatted drive

**Comment by thebsdbox** [comment]
Steps 1/2 would typically be pre-Tinkerbell in order to generate an image, whereas step 3 would be implemented within a workflow.

**Comment by jacobweinstock** [comment]
Hey @nwmcsween, there is now a guide for windows that can be found here: https://docs.tinkerbell.org/deploying-operating-systems/examples-win/
Hope that is what you're looking for!

**Comment by jacobweinstock** [comment]
Hey @nwmcsween, there is now a guide for windows that can be found here:
https://docs.tinkerbell.org/deploying-operating-systems/examples-win/

Hope that is what you're looking for! If this is not please do reopen this.
