### ISSUE TITLE
Let's adopt Bors to merge PRs

### ISSUE THREAD

**Issue by grahamc** [tinkerbell/tink#145]
The "require being up to date with master before merging" restriction is a good idea, but makes it really tricky to merge PRs. We could get this same benefit but with automation and without the race to merge a PR by using  bors:  https://bors.tech/

All we have to do is click enable here: https://github.com/apps/bors and read https://bors.tech/documentation/getting-started/

I propose adding this to all the tinkerbell repos.

**Comment by dustinmiller1337** [comment]
This looks cool :+1:

**Comment by gauravgahlot** [comment]
@grahamc Can we also look at [Mergify](https://mergify.io/) as an alternative to Bors?
It uses a configuration file ([like this one](https://github.com/infracloudio/botkube/blob/develop/.mergify.yml)) and allows us to have customization that best suits our needs.

**Comment by grahamc** [comment]
Absolutely. Any chance you could have a merging config file PR for Standup today?

**Comment by grahamc** [comment]
Mergify* of course. Autocorrect is a bear.

**Comment by gauravgahlot** [comment]
Done. #148
