### ISSUE TITLE
Setup v2.0 

### ISSUE THREAD

**Issue by gauravgahlot** [tinkerbell/tink#146]
```
## document what each section does (in detail)

# prereqs
	- docker 
	- docker-compose 
	- curl
	- git

# generate 'envrc'

# download osie (s3)
	- inputs from Manny about trimmed osie.tar

# basic network config
	- distro specific
		- minimal distro support
		- list supported distros in docs
	- skip (configure yourself)
		- manual setup docs
	
# generate certs

# registry setup
	- docker daemon config
	- push worker and fluentbit images

# docker-compose up
	- depends_on 
	- health_checks


```

**Comment by grahamc** [comment]
WIP PR at #147

**Comment by alexellis** [comment]
@gauravgahlot thanks for the ping on Slack

I'd like to see the download verified by SHA before unpacking.

There should be a way to bring the compose back up without having to run setup.sh ideally, right now it depends on ENV-vars captured during setup.sh - so could they be written into an env file?

Why is ifupdown used if Netplan is now the standard on Ubuntu and similar systems? Would it make sense to use that instead?

I believe I've re-generated the certs at least once or twice and then had a corrupted installation. I've also seen several people get stuck with restarting their provisioner machine, after one week powered-down, I couldn't reconcile my setup.

**Comment by fransvanberckel** [comment]
Beware, today it's all about Kubernetes. And about Ansible. Okay lets us face a minimal one, k3os. So you can skip the whole network part.

- https://k3os.io/

**Comment by gauravgahlot** [comment]
@grahamc @mrmrcoleman I think we can close it now.

**Comment by gauravgahlot** [comment]
Closing this one. New issues may be created in future.

**Comment by alexellis** [comment]
Hi, have you moved over to Netplan when installing on Ubuntu LTS (my main concern)?

**Comment by gauravgahlot** [comment]
Yes, we have.
https://github.com/tinkerbell/tink/blob/master/setup.sh#L82
