### ISSUE TITLE
Provide a way to snoop the TLS connections with WireShark

### ISSUE THREAD

**Issue by rgl** [tinkerbell/tink#162]
To better troubleshot/debug the entire tinkerbell ecosystem we need a way to snoop the TLS connections (e.g. using the `SSLKEYLOGFILE` environment variable as in [this go example](https://github.com/rgl/tls-dump-clienthello/blob/c12eb9370c74d0b3ff3618604ef06957feb2e3fc/main.go#L290-L300)) or a way to disable TLS.

The WireShark configuration is described at their [Using the (Pre)-Master-Secret](https://wiki.wireshark.org/TLS#Using_the_.28Pre.29-Master-Secret) wiki page.

**Comment by gianarb** [comment]
I see this as an opportunity for community members or maintainers if they use this techniques to blog about it.
Right now we have a not that detailed [troubleshooting document](https://tinkerbell.org/troubleshooting/) that we can refer the blog post too. And an issue about [Contrib documentation](https://github.com/tinkerbell/tinkerbell.org/issues/107).

if you are working with Wireshark and you need some pointers from a Tink prospective reach out to me via Slack I am happy to collaborate on this.
