### ISSUE TITLE
Why are the examples using the /statedir volume bind?

### ISSUE THREAD

**Issue by rgl** [tinkerbell/tink#163]
The examples (e.g. [Concepts template](https://github.com/tinkerbell/tink/blob/31888f40fd17f438ce828fcd44a6059cec4a8bd5/docs/concepts.md#template)) are using the `/statedir` but why use that volume when the [tinker-worker is automatically mounting `/workflow`](https://github.com/tinkerbell/tink/blob/7b55e2d62ee98670e04eb2f7e70c8ff4d60e3368/cmd/tink-worker/action.go#L185)?

**Comment by thebsdbox** [comment]
After going through a few workflows the following describes the usage:

- `/workflow` is used to contain mainly metadata information
- `/statedir` is used to contain information or "state" that happens between running containers was part of a workflow.

**Comment by gianarb** [comment]
After a chat with Thom, I am assigning this issue to @DailyAlice to double-check if something has to be added to the documentation. Otherwise, feel free to close it!

Thanks!

**Comment by DailyAlice** [comment]
I don't think that there is anything specific here that can be added to the docs at this time. I'll make a note of it though, there is probably a larger doc that can be written around Workers and container behaviors.
