### ISSUE TITLE
Smoke or E2E tests

### ISSUE THREAD

**Issue by gauravgahlot** [tinkerbell/tink#169]
The idea is to have smoke or E2E tests that:
 - setup a provisioner and a worker with Vagrant
 - execute a workflow
 - be part of the CI pipeline

Initial tests may cover the following workflows:
 - hello-world
   - services covered - tink, boots, osie
 - install Alpine Linux on worker
   - services covered - tink, boots, osie, hegel, cacher

**Comment by gauravgahlot** [comment]
@mrmrcoleman @grahamc 
Please update the description if I've missed anything from our discussion.

**Comment by mrmrcoleman** [comment]
Hey @gauravgahlot it would also be good to consider which events should trigger the CI. The end to end covers all (?) of the services, so does it run whenever any of the repos change?

**Comment by mrmrcoleman** [comment]
@gauravgahlot Which example are you going to use for the alpine work? (install Alpine Linux on worker)

**Comment by gianarb** [comment]
@gauravgahlot did you already select a target platform for CI/CD? I doubt github action, circleci, travis allowed to use vagrant.
Maybe @grahamc knows more because he tweeted about this

**Comment by mmlb** [comment]
our internal drone.packet.net exists *solely* to run VMs (for osie tests) :D, we can use it.

**Comment by mmlb** [comment]
But its an older version of drone. We can fire up a separate setup off of latest drone.io version and that way also keep external stuff off of our internal build hosts.

I can't recall if semaphore or circle ci let us bring our own build agents and thus allow us to run VMs in them.

**Comment by gianarb** [comment]
@mmlb do you think it is useful to setup e2e tests in a way that they can support multiple platform? Right now we have

1. Vagrant
2. Packet

Tomorrow we will may have something else and the workflow I am picturing is the one we have for kubernetes.

1. PR comes in somebody review it and when it is ready to get tests e2e it adds the label
2. When the label is there one job per platform starts and reports its status
3. You can retest with a comment like:

```
/retest vagrant
/retest packet
```

Ideally, this does not even need a runner that supports VMs because we will reach packet-api and use a device (or more based on the tests itself) for every build.

Does it have a sense? Or is it too much? 😄

**Comment by mrmrcoleman** [comment]
My 2 cents.

For Vagrant we'd want to test it in the way the user would use it. This means we'll need a build runner that supports virtualization.

I think testing the actual workflows might be tricky, but happy to think through it with you.

**Comment by gianarb** [comment]
Today I got some time and I tried the Getting Started with Vagrant tutorial inside a Packet machine. I got it running apart for the worker that requires a GUI and we do not have it:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "19c0ccd6-9a38-4ee0-9330-29e413387eee", "--type", "gui"]

Stderr: VBoxManage: error: The virtual machine 'vagrant_worker_1594815205261_61888' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

## How I did it

1. Create a machine on packet

```console
packet device create --operating-system ubuntu_20_04 --plan c1.small.x86 --project-id f49cf84 --hostname tink-e2e --facility ams1
```

2. ssh into it and run:

```
#!/bin/bash

apt-get install -y linux-generic linux-image-generic linux-headers-generic virtualbox
```

At this point you can follow the Getting Started until the end.

**Comment by gauravgahlot** [comment]
I tried executing an Ubuntu provisioning workflow on my local Vagrant setup without GUI. It was successful. 
```
vagrant@provisioner:/vagrant/deploy$ docker-compose exec tink-cli tink workflow events 096f328e-6286-4aff-ada6-93e8eec38f96
+--------------------------------------+-----------------+-----------------+----------------+---------------------------------+--------------------+
| WORKER ID                            | TASK NAME       | ACTION NAME     | EXECUTION TIME | MESSAGE                         |      ACTION STATUS |
+--------------------------------------+-----------------+-----------------+----------------+---------------------------------+--------------------+
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | disk-wipe       |              0 | Started execution               | ACTION_IN_PROGRESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | disk-wipe       |             16 | Finished Execution Successfully |     ACTION_SUCCESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | disk-partition  |              0 | Started execution               | ACTION_IN_PROGRESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | disk-partition  |              4 | Finished Execution Successfully |     ACTION_SUCCESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | install-root-fs |              0 | Started execution               | ACTION_IN_PROGRESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | install-root-fs |             22 | Finished Execution Successfully |     ACTION_SUCCESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | install-grub    |              0 | Started execution               | ACTION_IN_PROGRESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | install-grub    |             13 | Finished Execution Successfully |     ACTION_SUCCESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | cloud-init      |              0 | Started execution               | ACTION_IN_PROGRESS |
| 0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94 | os-installation | cloud-init      |              0 | Finished Execution Successfully |     ACTION_SUCCESS |
+--------------------------------------+-----------------+-----------------+----------------+---------------------------------+--------------------+

```

Then to access the worker I had to do:
```
vagrant halt worker

// set GUI to true in Vagrantfile

vagrant up worker
```
