### ISSUE TITLE
./setup.sh registry:2 htpasswd: not found

### ISSUE THREAD

**Issue by fransvanberckel** [tinkerbell/tink#179]
While clone today's git repo I have got this error ...

-- Step 6/7 : RUN htpasswd -Bbn ${REGISTRY_USERNAME} ${REGISTRY_PASSWORD} > /auth/htpasswd
 ---> Running in 44f85abb48dc
Service 'registry' failed to build: The command '/bin/sh -c htpasswd -Bbn ${REGISTRY_USERNAME} ${REGISTRY_PASSWORD} > /auth/htpasswd' returned a non-zero code: 127

-- Details:
Building registry
Step 1/7 : FROM registry:2
2: Pulling from library/registry
cbdbe7a5bc2a: Already exists
47112e65547d: Pull complete
46bcb632e506: Pull complete
c1cc712bcecd: Pull complete
3db6272dcbfa: Pull complete
Digest: sha256:8be26f81ffea54106bae012c6f349df70f4d5e7e2ec01b143c46e2c03b9e551d
Status: Downloaded newer image for registry:2
 ---> 2d4f4b5309b1
Step 2/7 : RUN apk add --no-cache --update curl
 ---> Running in fec0dfe9b1d7
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/3) Installing nghttp2-libs (1.40.0-r1)
(2/3) Installing libcurl (7.67.0-r0)
(3/3) Installing curl (7.67.0-r0)
Executing busybox-1.31.1-r9.trigger
OK: 7 MiB in 18 packages
Removing intermediate container fec0dfe9b1d7
 ---> f56293403c8b
Step 3/7 : ARG REGISTRY_USERNAME
 ---> Running in 4537df57c6e8
Removing intermediate container 4537df57c6e8
 ---> 427b616aa53e
Step 4/7 : ARG REGISTRY_PASSWORD
 ---> Running in 9a70e2c59126
Removing intermediate container 9a70e2c59126
 ---> 1f7a9b6eff71
Step 5/7 : RUN mkdir -p /certs /auth
 ---> Running in 4cbd68dda8f6
Removing intermediate container 4cbd68dda8f6
 ---> ccbf71badcc5
Step 6/7 : RUN htpasswd -Bbn ${REGISTRY_USERNAME} ${REGISTRY_PASSWORD} > /auth/htpasswd
 ---> Running in 44f85abb48dc
/bin/sh: htpasswd: not found
ERROR: Service 'registry' failed to build: The command '/bin/sh -c htpasswd -Bbn ${REGISTRY_USERNAME} ${REGISTRY_PASSWORD} > /auth/htpasswd' returned a non-zero code: 127

**Comment by mrmrcoleman** [comment]
@fransvanberckel We're aware of this issue and the fix is awaiting approval here: https://github.com/tinkerbell/tink/pull/178

It seems that `apache2-utils` was removed from the upstream registry imagine in 2.7. Pinning the registry version to 2.6.2 in `./deploy/registry/Dockerfile` fixes the issue.

**Comment by fransvanberckel** [comment]
Patched the Dockerfile, it's running ./setup.sh again ... ;-)
Thanks for supporting.
