### ISSUE TITLE
Vagrant: tink hardware push rpc error: code = Unavailable

### ISSUE THREAD

**Issue by fransvanberckel** [tinkerbell/tink#187]
While today's setup by Vagrant example, have got this error ...

- https://tinkerbell.org/setup/local-with-vagrant/

-- Now we define our hello world template and load it into Tinkerbell:
vagrant@provisioner:/vagrant/deploy$ docker exec -i deploy_tink-cli_1 tink template create --name hello-world < ./hello-world.yml

Created Template:  4b7b9b74-a859-4d5f-a5b8-003858b3c9d4

-- Next we register the worker with Tinkerbell:
vagrant@provisioner:/vagrant/deploy$ docker exec -i deploy_tink-cli_1 tink hardware push < ./hardware-data.json

2020/06/23 08:21:44 rpc error: code = Unavailable desc = transport is closing

**Comment by mrmrcoleman** [comment]
Hoi @fransvanberckel this is caused by a breaking change to our hardware data model. My apologies for the inconvenience.

I've created a PR for the docs with an updated `hardware-data.json` example here: https://github.com/tinkerbell/tinkerbell.org/pull/86

**Comment by fransvanberckel** [comment]
Hi @mrmrcoleman,

Thanks, are willing to create a PR for the hello world example as well?

- https://github.com/tinkerbell/tink/blob/master/docs/hello-world.md

**Comment by gauravgahlot** [comment]
@fransvanberckel Are you still facing this issue?

**Comment by fransvanberckel** [comment]
No not any more. With the new Vagrant example from the Tinkerbell website, it's solved.
