### ISSUE TITLE
Create a Ansible playbook for deploy

### ISSUE THREAD

**Issue by fransvanberckel** [tinkerbell/tink#189]
If we create a Ansible playbook for deploying Tink, what should be reflected?

**Comment by fransvanberckel** [comment]
I created a Ansible playbook for Tinkerbell
-- https://github.com/fransvanberckel/ansible-role-tinkerbell

**Comment by gianarb** [comment]
Yes! I think for now I will close this issue! 
Thank you for your help with the Ansible role!
