### ISSUE TITLE
How to use and set the Ephemeral Data?

### ISSUE THREAD

**Issue by rgl** [tinkerbell/tink#194]
https://github.com/tinkerbell/tink/blob/master/docs/concepts.md#ephemeral-data describes that we can use and access Ephemeral Data, but how are we supposed to do that?

Is there a way to bootstrap the workflow ephemeral data when we create the workflow?

Reading the code it seems that tink-worker will sync the `/workflow/data` file (and not the `/workflow/data.json` as depicted in the documentation) with hegel when a workflow starts/ends, is that really what is happening?

For reference, this is the part of the code that reads and writes the `/workflow/data` file to hegel:

* https://github.com/tinkerbell/tink/blob/8e7e17042fbbe3cf92fc7e37983c9943fb3c76ee/cmd/tink-worker/worker.go#L150
* https://github.com/tinkerbell/tink/blob/8e7e17042fbbe3cf92fc7e37983c9943fb3c76ee/cmd/tink-worker/worker.go#L192

**Comment by ScottGarman** [comment]
Thanks for this issue report. I believe we have much improved documentation on this now, see the Ephemeral Data section on this page: https://docs.tinkerbell.org/workflows/working-with-workflows/. If there is something still missing from this doc, please open a new issue with details.
