### ISSUE TITLE
Introduce a Contribution Guide

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#201]
A Contribution Guide helps set expectations on what is required before making a contribution to an open source project.

It also can be used to discuss style and approach to how the team wants:

* code to be structured and tested
* where to go to get help
* how to become a maintainer
* any conventions required or tooling like linters
* whether a CLA or DCO is required (#202)
* how to find issues to work on - i.e. tags 
* what each repo is for and how to work on it
* how the project accepts proposals
* whether a proposal is needed before someone makes a feature change

OpenFaaS has a relatively well-defined guide: 
https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

The guide for inlets is much less verbose: 

https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md

Kubernetes contributing guide (requires you to sign a CLA, see also #202)

https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md

Moby project

https://github.com/moby/moby/blob/master/CONTRIBUTING.md

As a contributor, I'd like to see the team start a contributing guide and to have it published in the main tinkerbell/tink repo or in the .github repo.

**Comment by rainleander** [comment]
Agreed and I'm keen to help. Where would you like to start this project?

**Comment by alexellis** [comment]
> Where would you like to start this project?

I can advise the team on what to include, but I can't write this for you because it's really for the maintainers to decide what the process is going to be.

As for where - it would need a PR to this repo, but there is a chance that the .github repo can be used to make it appear in each. Perhaps you could identify the key maintainers and ping them in this thread?

Alex

**Comment by mrmrcoleman** [comment]
@thomcrowe I think I heard you say you'd started on this, is that correct?

**Comment by gianarb** [comment]
I pinged @thomcrowe on salck, he is working at it!

**Comment by gauravgahlot** [comment]
Since we have the [CONTRIBUTING.md](https://github.com/tinkerbell/tink/blob/master/CONTRIBUTING.md) in place, I'm closing this issue.
