### ISSUE TITLE
Consider legal implications of open source contributions

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#202]
The team may want to consider the legal implications of taking open source contributions from a broad audience. There are risks involved particularly when a copyright claim might arise or code is contributed where an employee is not authorised to do so.

There are two common approaches that you will see in commercial open-source and in independent projects.

The Linux kernel uses the Developer Certificate of Origin - which is according to Wikipedia "a legal agreement" that the code being submitted to the project is an original work and that the author has permission to do so. This is done with a message at the end of each commit "Signed-off-by:" - it is not to be confused with cryptography (GPG signing) and works through trust.

[Read the DCO agreement](https://developercertificate.org)

Docker, OpenFaaS, inlets and many other OSS projects use a DCO. It likely does not need to involve a legal team and is self-explanatory.

The other that Azure and Hashicorp projects use is the CLA - [Contributor License Agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement):

>CLAs can be used to enable vendors to easily pursue legal resolution in the case of copyright disputes,[1] or to relicense products to which contributions have been received from third parties.[2] CLAs are important especially for corporate open source projects under a copyleft license, since without a CLA the contribution would restrict the guardian as well.

> The purpose of a CLA is to ensure that the guardian of a project's outputs has the necessary ownership or grants of rights over all contributions to allow them to distribute under the chosen license. In some cases this will mean that the contributor will assign the copyright in all contributions to the project owner; in other cases, they will grant an irrevocable license to allow the project maintainer to use the contribution. CLAs also have roles in raising awareness of IPR issues within a project.[3]

You will see many large organisations listed that are using a CLA.

**Comment by mmlb** [comment]
We do *not* want to go with CLAs, and should very much do DCO requirements. I think we just overlooked it in the rush of activity.

**Comment by alexellis** [comment]
When the time comes - enforcement is important and it's very easy to miss so automation helps with that.

Several OSS projects use Derek to enforce a DCO on commits and to allow listed contributors (not org admins) to open/close issues / PRs etc. https://github.com/alexellis/derek/

It's a free SaaS that is operated for the community - goreleaser / Docker / oketeo are using it.

**Comment by mmlb** [comment]
I like the idea of using Derek, but not specifically for this task. I think https://probot.github.io/apps/dco/ would match up better with our use of Mergify since it blocks the PR via status checks. 

Is there any plans in Derek to parse out CODEOWNERS file?

**Comment by alexellis** [comment]
Why do you feel Derek doesn't fit? What do you feel is needed for that to change?

**Comment by alexellis** [comment]
We found a bug in the probot that it couldn't detect an invalid DCO where one of the N commits was not signed off but the last was. I suspect that's still the case. 

All commits need to be signed off, PRs are not what are kept in git history, commits are.

**Comment by mmlb** [comment]
> Why do you feel Derek doesn't fit? What do you feel is needed for that to change?

Derek blocking via status checks that we can require in the branch protection settings would be ideal. Changing the label Derek applies to `do-not-merge` would work, but not as well I think.

> We found a bug in the probot that it couldn't detect an invalid DCO where one of the N commits was not signed off but the last was. I suspect that's still the case.
> 
> All commits need to be signed off, PRs are not what are kept in git history, commits are.

https://github.com/probot/dco/issues/121 seems to indicate that this has been fixed. I plan to check it out.

**Comment by alexellis** [comment]
In the linked issue, I can't see that the issue was fixed in probot, just that someone else also found it. I might be missing something though.

For my understanding: Does the `do-not-merge` label have specific significance to your workflow, or is that just your reference over the `no-dco` label?

There is work to block statuses, however, this may be the reason that probot has a bug - the status checking only works against each commit in the PR, not the PR as a whole entity, so typically the "merge" button is only looking at the last commit, not the whole set.

You should definitely test that scenario before adopting probot, but it is covered by Derek today, minus the status blocking. https://github.com/alexellis/derek/pull/108

**Comment by mmlb** [comment]
The linked issue mentions that the fixup help message is inaccurate, that it does not correctly message how to fix a non-dco commit in history that is not the latest commit.

Either way, I just tested on a personal repo and the app correctly identified all commits missing dco, followed by latest commit good but previous missing, and then all commits with DCO.

do-not-merge is how we've setup mergify to disable attempts to merge, but that only applies once all the required GH status checks are green. IMO this is perfect place for tools to interject and block PRs.

**Comment by gianarb** [comment]
Hello!

Just a heads up @mmlb enabled just now https://probot.github.io/apps/dco/ for all repositories. 

I will close this issue for now because @thomcrowe  will mention what's needed about this process as part of #201 .
