### ISSUE TITLE
Vagrant: Boots service in perpetual reboot

### ISSUE THREAD

**Issue by I-Lopez** [tinkerbell/tink#203]
I'm trying to run through the Vagrant guide, but Boots does not stand after running `docker-compose up -d`

This screenshot shows the warnings once the above command is executed. 
![image](https://user-images.githubusercontent.com/33550693/86387036-96234e80-bc60-11ea-9e4c-34331c12cdda.png)

This one shows the results of `docker-compose ps`
![image](https://user-images.githubusercontent.com/33550693/86387270-f1edd780-bc60-11ea-8149-114a3fd027bc.png)

The results of the log command `docker-compose logs -f tink-server boots nginx` are below. 
![image](https://user-images.githubusercontent.com/33550693/86387618-6d4f8900-bc61-11ea-9907-f8da6e7ce1df.png)

Boots will try to deploy with the message `deploy_boots_1 exited with code 2` before trying again.

## Steps to Reproduce (for bugs)
1. Following the steps described in this page: https://tinkerbell.org/setup/local-with-vagrant/

Everything seems to work up until I run docker-compose commands.

## Context
I'm trying to follow the Vagrant guides to mess around with Tinkerbell. I have tried using different network names in the envrc file to see if that has anything to do with it, but the results don't change from the ones shown above. Running the docker-compose commands as `sudo` make it so many of the envrc environment variables are blank strings.

## Your Environment
I'm running the latest version of MacOS Catalina. I'm following the Vagrant with Virtual Box guide. I'm not sure what other details can help, but I have Docker Desktop installed on my machine as well. 

Thank you for the time.

**Comment by I-Lopez** [comment]
This is the correct screenshot of the `docker-compose up -d` command:
![Screen Shot 2020-07-02 at 12 36 38](https://user-images.githubusercontent.com/33550693/86389581-83ab1400-bc64-11ea-979e-b3b0a3c071aa.png)

**Comment by parauliya** [comment]
Hi @I-Lopez, 
I just ran the same setup on my local machine and it is working fine. There is no issue with boots. 
After looking at your logs I feel like there is a possibility that your boots image might not be the latest one. 
Could you please destroy the current setup completely and try that again and let us know if you face the same issue again?

Thanks,

**Comment by I-Lopez** [comment]
This worked thank you!
