### ISSUE TITLE
Proposals for enhancement on tinkerbell 

### ISSUE THREAD

**Issue by Cbkhare** [tinkerbell/tink#217]
**1**) Fault tolerant provisioner:
**problem**: Currently the provisioner runs only on single machine. If that machine goes down, tinkerbell as a setup would become unresponsive and worker machines can go into undesirable state.
proposal:
**solution**:
a) Setup should be in HA state. provisioner should have more than one instance, could be in active-passive. State of provisioner should be consistent and should also ensure availability.
b) provisioner server should be cluster of all services (ex, hegel, boots) wrapped in a private network. Worker (..etc) connects to the proxy exposed on provisioner cluster to connect to.

**2**) Move all tinkerbell services in private Network and expose them via proxy:
**problem**: Currently all the services in provisioner are accessible from outside (i.e via worker). Even in some implementation, ex tink #195, worker have full access (Read+write) tink-server via tink client. This leads to possibility that worker can alter the behaviour of tink-server.
**solution**:
a) move all the tink-services in a private network. All the services should be accessible only via proxy.
b) worker should only have read access. I have suggested in #195, that we should dynamically assosiate worker id to every grpc call made from worker node. This would ensure, worker does not have access to atributes of other workers.
c) tink-server should not expose method (like, GetWorkflowContexts,) directly to worker. Instead, tink-server should expose wrapper function, which would internally call the respective methods with additional validations.
	
```
func wrapper_to_get_workflow(){
	   validate worker_id and state
	   call getWorkflow
	   return
	} 
	worker calls -->  some_data = wrapper_to_get_workflow()
```

**3**) Logging:
**problem**: logging from worker and other provisioner servies should be pushed to server.
**solution**: Implement a logging aggregator. aggregator should have the ability to collect logs consistently sent via grpc calls.

**Comment by gianarb** [comment]
Hello @Cbkhare ! I am gonna close this for now. I think it will be nice if we can elaborate those time of questions more in their own [proposals](https://github.com/tinkerbell/proposals), now that we have them! 

Thanks!
