### ISSUE TITLE
Worker should have only read access to tink-server

### ISSUE THREAD

**Issue by Cbkhare** [tinkerbell/tink#218]
Worker make grpc requests to tink-server. Worker has currently access to all the grpc methods and uses them for some process. This also enables the worker to modify the attributes inside the tink-server. 

## Expected Behaviour
a Worker would have only read access to tink-server grpc methods and should only access attributes specific to it. 

## Current Behaviour
Worker has full access to tink-server. 

## Possible Solution
It can be achived by dynamically adding worker Id to rpc requests.  Also wrapper method should be added for worker methods instead of directly exposing all the methods

## Context
It can create security issues.

**Comment by gianarb** [comment]
I think this is a much bigger issue. To make it right we need RBAC or something similar.

**Comment by gianarb** [comment]
I am gonna close this for now because that's not right. tink-worker needs to report back to tink-server the status of the action it executes.

I agree we should make it clear and it should have limited access but for that it needs access control
