### ISSUE TITLE
Document all public interfaces

### ISSUE THREAD

**Issue by displague** [tinkerbell/tink#219]
## Expected Behaviour

As a developer, the interfaces of the client should be easy to work with.

The endpoints should be documented in a way that describes what the purpose of each endpoint is and what the parameters do.

## Current Behaviour

Endpoints are not documented: https://github.com/tinkerbell/tink/blob/0100e535bd94c14b95eeedbbe46c576d1f344301/protos/hardware/hardware.pb.go#L2023

This makes features like #195 (OpenAPI generated documentation and clients) less valuable.

## Possible Solution
Document (as code comments) each of the public functions, types, and fields for the 3 Client interfaces.
https://github.com/tinkerbell/tink/blob/master/client/main.go#L66-L68

**Comment by gianarb** [comment]
Hello @displague ! Thank you for opening this PR. I think comments has to be improved and you identify a very valuable place to start with!

Are you interested in opening a PR with the 3 comments you suggested?! 

Thanks

**Comment by rugwirobaker** [comment]
I'm just getting started going through the codebase and I think this would be very much helpful. If no else has I'd like to pick up.
