### ISSUE TITLE
registry: No HTTP secret provided - generated random secret

### ISSUE THREAD

**Issue by fransvanberckel** [tinkerbell/tink#225]
Is there something fundamentally changed in the password logic for registry? Some weeks a go, we added apache2-utils (read for htpasswd) to the Dockerfile, because it wasn't in the image any more.

https://github.com/tinkerbell/tink/commit/3212aa49df2571e62f2ea24a53cd88c26c3d6804

And if i check the logs now, i am getting ...

-- registry_1 | time="2020-07-25T08:26:13.379776536Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.11.2 instance.id=374a175e-17af-4c5b-a3d9-e08189c7b113 service=registry version=v2.7.1

**Comment by gianarb** [comment]
Hello @fransvanberckel 

No, the registry version or the image did not change for what I can see scanning the git history for the project. I tried to setup Tinkerbell via Vagrant and I see I have the same log but after that everything works fine. I think it was always there.

it is a warning that causes issues only if there are multiple registries behind the same load balancer. This is something that we do not cover yet in our setup scripts.

if you are working with an HA Tinkerbell installation I think you have to provide an HA registry

**Comment by fransvanberckel** [comment]
Hello @gianarb

I am not having any practical issue. It's just a warning.

**Comment by gianarb** [comment]
Great thanks, I will close this issue for now 👍
