### ISSUE TITLE
Create a Kubernetes deployment

### ISSUE THREAD

**Issue by displague** [tinkerbell/tink#226]
## Expected Behaviour

Tinkerbell should be installable via `kubectl apply ...` or `helm install ...`.

## Current Behaviour

Tinkerbell is not installable in Kubernetes.

## Possible Solution

Create manifests for Kubernetes installations.

This requires that images are published.
* [x] https://quay.io/organization/tinkerbell (amd64)
* [ ] The images should be multiarch so the Kubernetes install works on ARM (Raspberry Pis).

This requires that Kubernetes manifests:
* [ ] Exist for `kubectl apply`

And these manifests have optionally:
* [ ] Have been adapted for Kustomize patches
* [ ] Have been adapted to Helm install and publishing

## Your Environment

Kubernetes 😄

**Comment by displague** [comment]
I converted the docker-compose environment from https://github.com/tinkerbell/tink/tree/master/deploy into an initial set of manifests: https://github.com/displague/tink-charts. 

These currently lack any documentation on the configuration steps necessary to make them usable, because I am still tinkering with them.

I am using this on Raspberry Pis.  When installing these manifests, I ran into the lack of multi-arch builds for the various services.

* https://github.com/tinkerbell/boots/issues/4
* https://github.com/tinkerbell/hegel/issues/21
* tink-server
* tink-cli
* https://github.com/tinkerbell/pbnj/issues/6

**Comment by displague** [comment]
@matoszz directed me to https://github.com/tinkerbell/tink/wiki/RFC-%233-Kubernetes-Support which covers the changes needed to get Tinkerbell running from Kubernetes from the perspective of a CRD controller handling the data.

This issue was opened with the expectation of using CSI or local-path volumes to persist data. I think this is a shorter path to running Tinkerbell within Kubernetes. A CRD based approach would overcome the persistent data hurdles (especially in the case of running K3s+Tinkerbell on a single Raspberry Pi node 😄 ).

Such a change could potentially remove the need for PBNJ and PostgreSQL, if the other services use Kubernetes resources as the source of truth.  The controller would effectively replace PBNJ and Kubernetes resources would replace PostgreSQL.

Without a bespoke API, tink-cli could become a Kubectl plugin that affects Kubernetes CRDs.

The CRDs that would be needed would map to the existing database tables (and tink-cli commands):

* Hardware
* Workflow
* Template

**Comment by displague** [comment]
#364 offers charts that may check some of the boxes on this issue.

**Comment by detiber** [comment]
I created https://github.com/tinkerbell/k8s-sandbox as a place that we could use for Kubernetes related work.

**Comment by invidian** [comment]
See also https://github.com/tinkerbell/tink/issues/335

**Comment by displague** [comment]
Closing this in light of https://github.com/tinkerbell/k8s-sandbox/tree/main/deploy/kubernetes
