### ISSUE TITLE
Remove unnecessary references to Packet

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tink#227]
I think we should remove the word Packet if not necessary like here:

https://github.com/tinkerbell/tink/blob/850584d46c8d5d7aaee3868f13fa5aede97ac32b/http-server/http_server.go#L80

**Comment by thebsdbox** [comment]
I agree as this is a bit unnecessary, also most servers have "standardised" on `/healthz` as detailed here -> https://vimeo.com/173610242
