### ISSUE TITLE
Move terraform deployment to a separate repository

### ISSUE THREAD

**Issue by displague** [tinkerbell/tink#228]
## Expected Behaviour

The terraform deployment should be stable and published in the terraform.io registry.

## Current Behaviour

* `deploy/terraform` falls out of sync with the shared setup.sh (used by the Vagrant installer).
* The project not can be used as a module from the terraform registry

## Possible Solution

* Move terraform deployment to a new terraform-packet-tinkrbell repository.
* Publish this module

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by displague** [comment]
I have started with this in github.com/displague/terraform-packet-tinkerbell

**Comment by invidian** [comment]
Isn't this done in https://github.com/tinkerbell/tink/pull/289 ?

**Comment by gianarb** [comment]
Yep thanks
