### ISSUE TITLE
Support provisioning RPi

### ISSUE THREAD

**Issue by zsmith928** [tinkerbell/tink#24]
We should support an easy homelab deployment model for Tinkerbell, such as supporting RPi with UEFI (https://rpi4-uefi.dev/) or PXE ([doc](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md)) .  The goal would be to run core services on a local laptop or computer and lifecycle RPi 3 or RPi 4 devices.

**Comment by andreiw** [comment]
that would be very cool

**Comment by Ottovsky** [comment]
I am very interested in this feature. I want to build out a home lab with rpi4 and configure k8s on top of it by leveraging tinkerbell workflows.

**Comment by mrmrcoleman** [comment]
Relevant repo from Container Solutions: https://github.com/ContainerSolutions/tinkerbell-rpi4-workflow

**Comment by Ottovsky** [comment]
We do also have an example with the mentioned rpi4-uefi, which does not require the workarounds with nfs:  https://github.com/ContainerSolutions/tinkerbell-rpi4-workflow/tree/rpi4-tinkerbell-uefi

**Comment by tstromberg** [comment]
As far as I know, Raspberry Pi provisioning should work out of the box today. The aforementioned links are helpful to investigate the details.
