### ISSUE TITLE
Use goss and multi stage build to test docker images

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tink#246]
goss is a popular framework usable via docker that helps to check the status of a server/docker image.

https://github.com/aelsabbahy/goss-docker

A nice integration is to combine this with multi-stage build to change stage as the last step in Dockerfile to run the assertion [jumping back to the previous one](https://docs.docker.com/develop/develop-images/multistage-build/#use-a-previous-stage-as-a-new-stage), in this way we get the same image but with the assertions we wrote.

possible assertions:

* The binary is there
* The binary runs and returns the expected exit code

**Comment by tstromberg** [comment]
Closing until someone wants to decide to pick this task up.
