### ISSUE TITLE
Integration with netbox

### ISSUE THREAD

**Issue by nwmcsween** [tinkerbell/tink#253]
Integration with netbox.

Briefly looking over the code there would need to be glue between what tink takes and netbox provides, id in netbox is serial and such

**Comment by gianarb** [comment]
Thank you for opening this issue! I personally do not have any experience with netbox but I am sure it will be nice to experiment with it! If you have any detailed pointers to help me or other contributors to figure out where and how netbox plays in the stack it will make MY life easier. 

If you made any attempt with workflows let us know

**Comment by nwmcsween** [comment]
Netbox would replace the hardware.json db and possibly the workflow db.
Tink would pull from the netbox rest API instead of the postgresql
instance, the workflows could then use the netbox API to query for richer
metadata. The issues with integrating is Tink would require a few custom
fields and (UUID, storage, etc) created and depending on the number of
custom fields it might make sense to write a netbox plugin instead and
provide the expected JSON for tink. There is go-netbox or
https://netboxdemo.com/api/docs/ for openapi docs.

**Comment by ITJamie** [comment]
+1 on netbox support

**Comment by chrisdoherty4** [comment]
We're interested in integrating with Netbox but we're quite a ways off doing it. Given this issue doesn't have any movement and we're trying to separate roadmap from actionable issues this has been moved to our roadmap repository.

A project exists with a draft issue but the tracking may change as we figure out our roadmap process.

https://github.com/orgs/tinkerbell/projects/24
