### ISSUE TITLE
force / store mac lowercase

### ISSUE THREAD

**Issue by geekgonecrazy** [tinkerbell/tink#278]
I created a hardware definition copying directly from proxmox which shows mac address all capital letters.

So when boots queried using the lowercase mac address it would return "unexpected end of json"

## Expected Behaviour

Force / store mac address lowercase

## Current Behaviour

Errors out

## Possible Solution

Force lowercase

## Steps to Reproduce (for bugs)

1. insert
```
{"id":"0eba0bf8-3772-4b4a-ab9f-6ebe93b90a94","metadata":{"facility":{"facility_code":"ewr1","plan_slug":"c2.medium.x86","plan_version_slug":""},"instance":{},"state":"provisioning"},"network":{"interfaces":[{"dhcp":{"arch":"x86_64","ip":{"address":"10.10.6.2","gateway":"10.10.0.1","netmask":"255.255.0.0"},"mac":"E2:8A:5B:5E:45:3E"},"netboot":{"allow_pxe":true,"allow_workflow":true}}]}}
```
2.
boot vm or a machine with mac address.  Which will be sent to lowercase
3. fails to boot

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by detiber** [comment]
I created https://github.com/tinkerbell/tink/pull/279, which should address this issue

**Comment by geekgonecrazy** [comment]
Wow that was quick! 🙏
