### ISSUE TITLE
Event driven implementation

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tink#294]
This issue will be used as a way to summarize and centralize work required to solve proposal [[0012] Event driven system](https://github.com/tinkerbell/proposals/pull/17/)

The proposal is coming together and it is time to prototype and work on the actual implementation. The proposal contains directions and ideas about how it can be done, but the real work will be reflected here.

I want to split this work into two big pieces, ReadingPath and WritingPath.

## ReadingPath

The ReadingPath is around how events get out form tink-server. @gauravgahlot is currently having a look at this part.

### Phase 1

* How we can stream Events and serialize them via gRPC.
* How the EventClient and the `Watch` will look like
* Listen on the `event` table and stream out events

### Phase 2: 

* How we can filter events out
* Use the EventClient in the other client to build the `hardware.Watch` function.

### Prerequisite

None for now.

## WritingPath

This is all about how events are written in the database itself. It is for sure the part that has the fewest unknowns.
@parauliya  is currently looking at this.

### Phase 1

* Setup a new event table in Postgres
* Hook* only a bunch of events like:
     * CREATED, DELETED, UPDATED for the workflow resource
     * The event required for the phone home feature: 
           * WORKFLOW_STARTED
           * WORKFLOW_SUCCEEDED
           * WORKFLOW_TIMEOUT
           * WORKFLOW_FAILED
           * ACTION_STARTED
           * ACTION_SUCCEEDED
           * ACTION_TIMEDOUT
           * ACTION_FAILED

*hook means: find the right code path to write the event in Postgres and persist it!

### Phase 2

* Hook all the missing events
* Set up a listener for the event table and hook the ReadingPath with the WritingPath
* Write a garbage collector that cleans up old events, if Postgres does not have a similar feature already.

### Prerequisite

* https://github.com/tinkerbell/tink/issues/295 I noticed we do not really have a way to migrate the database. I think this is required to create the new event table for running tinkerbell. Other than being a better way to manage the database initialization (moving it from docker-compose to tink-server itself). Something like [golang-migrate/migrate](https://github.com/golang-migrate/migrate)

**Comment by mmlb** [comment]
Strongly suggest `Phase1` is done with triggers like https://wiki.postgresql.org/wiki/Audit_trigger_91plus
