### ISSUE TITLE
Integrate a migration tool in tink

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tink#295]
Tink uses Postgres as datastore.

There are two things I would like to achieve here:

1. We need a way to migrate our database schema as part of #294 . We need to add an `event` table at least.
2. Right now the database initialization is applied via docker-compose. I would like to have a more generic mechanism and even better if it can be managed by tink itself.

I explored a couple of libraries:

* https://github.com/amacneil/dbmate
    * 👍  their readme makes a comparison with the other libraries and dbmate looks like the best one ever!
    * 👎  their readme makes a comparison with the other libraries and dbmate looks like the best one ever!
    * 👎  it is in Go, so we can embed the library, but there is no documentation about how to do it
* https://github.com/golang-migrate/migrate
    * 👍  it has more starts that all the others and community is active for what I can tell
    * 👍  Packet used it internally already
    * 👍  It is designed with embeddability in mind as you can see from their README.
    * 👎  dbmate's README says that dbmate is cooler!
* https://github.com/kyleconroy/sqlc
    * 👎  It does not really do the migration, it is more like code generation from SQL.
    * 👍  I love this library but its not what I am looking for now, it works with dbmate and `migrate`. We should keep it in mind as a possible way to generate some of the code we write manually.

---

I think `migrate` is what I am looking for. As I said the migration will be applied at every boot (it is idempotent on its own, so if there are not migration to apply, we are good).

I will start with the fil source but I am investing the possibility to use a `custom` source (source is where migrations are read from) because I would like to have the migration file written in `*.go` and embedded in the binary itself, to simplify distribution.

**Comment by thebsdbox** [comment]
I'm a little confused with your 👍 👎 ranking, but if we're already using `migrate` and it is relatively active then it seems like the path of least resistance 👍

**Comment by rugwirobaker** [comment]
I can vouch for migrate too. The feature I like most is that I can embed my migrations in the binary using packr.

**Comment by Cbkhare** [comment]
I found this big list of `Go Schema Migration tools` with good comparisons. May it can also help. 

https://povilasv.me/go-schema-migration-tools/ 

Moreover, https://github.com/golang-migrate/migrate seems to be a good choice.

**Comment by gianarb** [comment]
@Cbkhare the article is good but published in `PUBLISHED FEBRUARY 20TH, 2017`. In Go it means FOREVER! eheh

@thebsdbox those are pros and cons based on my judgment

I am evaluating the lib @rugwirobaker shared because I like how it looks easy to embed
