### ISSUE TITLE
Delete pkg package

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#300]
pkg packages is an anti pattern. Instead we should break out its contents into smaller/easier to use packages.

**Comment by detiber** [comment]
+1000, we should also move anything that we don't intend to expose as a public API into one or more 'internal' packages

**Comment by vigneshashokan** [comment]
@mmlb If no one is working on this, I can take a stab at this issue.

**Comment by gauravgahlot** [comment]
@vigneshashokan I don't think anyone is working on it yet. I will assign the issue to you. 

Please take read at the [communication](https://github.com/tinkerbell/.github/blob/master/COMMUNICATION.md) doc and do let us know if you face any issues in the slack channel.

Looking forward to your contribution. 😄

**Comment by mmlb** [comment]
@vigneshashokan I've done one part in #315 already.

**Comment by chrisdoherty4** [comment]
Stale issue. Some of this work is being addressed with an overhaul of the Tink repository anyhow.
