### ISSUE TITLE
the file pull via curl is not robust and sometimes fail with out error / abort the script

### ISSUE THREAD

**Issue by MaxPeal** [tinkerbell/tink#306]
the file pull via curl is not robust and sometimes fail with out error / abort the script

## Expected Behaviour
curl must catch the errors and abort the script.

## Current Behaviour
curl will fail silently

## Possible Solution
see the PR #305 

## Steps to Reproduce (for bugs)
have a unstabel network

## Your Environment
local Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
linux 
* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
Vagrant & VirtualBox

**Comment by tstromberg** [comment]
Reopening because #519 does not actually fix the issue.
