### ISSUE TITLE
Support specifying hardware in YAML

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#316]
## Expected Behaviour

As templates currently accept YAML, it would be nice if hardware could also be specified in the same format. It currently works other way round, as YAML is compatible with JSON, but IMO YAML is more common format and more human readable than JSON. I find it confusing, that different subcommands operates using different formats.

## Current Behaviour

Currently `tink hardware push` only supports JSON input.

## Possible Solution

Use YAML decoder rather than JSON decoder when taking hardware data from the user.

**Comment by MohammadRVR** [comment]
Hi, I would like to work on this. Please assign this to me

**Comment by jacobweinstock** [comment]
the kubernetes backend supports this. close by https://github.com/tinkerbell/tink/pull/654
