### ISSUE TITLE
Open transactions after validating data

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#318]
## Expected Behaviour

As validation code do not access the database, it can be executed outside transaction to reduce transaction time.

## Current Behaviour

Currently transaction is opened before data is validated, which extends lock time on database, which increases the latency on multiple requests: https://github.com/tinkerbell/tink/blob/master/db/template.go#L17-L30.

## Possible Solution

Validate data first, then open transaction.

**Comment by vbhv007** [comment]
Hey, Can I pick this up under hacktoberfest?
