### ISSUE TITLE
Consistently name client interfaces

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#319]
## Expected Behaviour

One can easily switch between working on code around workflows and templates and naming should follow the same convention, so interface names are not surprising, following [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

## Current Behaviour

- `github.com/tinkerbell/tink/protos/workflow` has `WorkflowSvcClient`
- `github.com/tinkerbell/tink/protos/hardware` has `HardwareServiceClient`
- `github.com/tinkerbell/tink/protos/template` has `TemplateClient`

**Comment by mmlb** [comment]
100% yes!

**Comment by mmlb** [comment]
Thanks @invidian take a look at #345 which addresses this along with other protobuf related warts I encountered.
