### ISSUE TITLE
Sample workflow - Debian

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tink#326]
## Expected Behaviour

A re-usable workflow that will deploy a version(s) of Debian

## Current Behaviour

We need to create more usable workflow examples that the community can start to use.

## Possible Solution

it could well be that we can work with @fransvanberckel and his workflow https://github.com/fransvanberckel/debian-workflow

## Context

The initial goal is to create a library of workflows within tinkerbell/workflows.. this repository will contain both the workflow `yaml` and the source code of the docker containers and scripts (in the first phase)

**Comment by gianarb** [comment]
Look at that! @thebsdbox wrote a doc about it
https://docs.tinkerbell.org/deploying-operating-systems/examples-debian/
