### ISSUE TITLE
Sample workflow - CentOS

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tink#328]
## Expected Behaviour

A re-usable workflow that will deploy a version(s) of CentOS

## Current Behaviour

We need to create more usable workflow examples that the community can start to use.

## Possible Solution

it could well be that we can work with @fransvanberckel and his workflow https://github.com/fransvanberckel/debian-workflow

## Context

The initial goal is to create a library of workflows within tinkerbell/workflows.. this repository will contain both the workflow `yaml` and the source code of the docker containers and scripts (in the first phase)

**Comment by Cbkhare** [comment]
Pr for the issue: https://github.com/tinkerbell/workflows/pull/5

**Comment by gianarb** [comment]
Our own @thebsdbox and @Cbkhare made it!
https://docs.tinkerbell.org/deploying-operating-systems/examples-rhel-centos/
Thanks
