### ISSUE TITLE
Sample workflow - Secure System Wipe

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tink#329]
## Expected Behaviour

A re-usable workflow that will perform a secure system wipe

## Current Behaviour

We need to create more usable workflow examples that the community can start to use.

## Possible Solution

Modifying the hello-world example to perform the required steps to wipe underlying disks?

## Context

The initial goal is to create a library of workflows within tinkerbell/workflows.. this repository will contain both the workflow `yaml` and the source code of the docker containers and scripts (in the first phase)

**Comment by benr** [comment]
Refer to the OSIE implementation: https://github.com/tinkerbell/osie/blob/688b5371b223d780e421614c800d1b22b9df8aef/docker/scripts/wipe.sh
