### ISSUE TITLE
Hardware Documentation - customising hardware spec

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tink#333]
## Expected Behaviour

Documentation that details:
- Modifying hardware JSON `spec` to pass additional kernel flags
- Passing a custom `kernel` or `initrd` 
- What is the usage of various parts of the JSON specification

## Current Behaviour

We currently have minimal documentation around the hardware specification and what it all means to an end user.

## Context

The current documentation shows a hardware specification but doesn't detail what a lot of it means, resulting in confused end-users when creating or debugging errors.

**Comment by chrisdoherty4** [comment]
See the ongoing documentation effort for more information https://github.com/tinkerbell/roadmap/issues/5
