### ISSUE TITLE
Tink CLI - create sample configuration

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tink#334]
## Expected Behaviour

The `cli` provides the capability to generate sample output that an end user can easily take as a starting point to modifying and customise to their own needs.

In Kubernetes an end user can accomplish something similar with the `--dry-run` flag that will create output instead of applying or creating a configuration.
```
$ kubectl create deployment my-dep --image=nginx --dry-run=client -o json
{
  ...
}
```

An *additional* benefit is that this would always generate output that matches the specification of the structs in the tinkerbell server.

## Current Behaviour

An end user has to take a large amount of json or yaml from docs and modify it to their own needs. We've seen issues where the docs haven't reflected changes to the yaml/json spec resulting in broken deployments. 

## Context

Simplify the UX for the end user

**Comment by jacobweinstock** [comment]
closed by https://github.com/tinkerbell/tink/pull/654
