### ISSUE TITLE
deploy/docker-compose.yml should be usable w/o setup.sh

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#367]
I like testing things on my laptop using docker-compose.yml. It's not easy to do so at the moment. I need to setup some env vars and generate certificates which is all orchestrated via setup.sh. I do not want to run setup.sh on my laptop as that tries to mess with certs and who know what else globally (I didn't check).

## Expected Behaviour

`cd deploy; docker-compose up --build -d` should get me a pretty good dev/test env.

## Current Behaviour

Lots of env vars missing, the docker-compose.yml isn't even valid and tink-server fails to start because tls certs are not generated.

## Possible Solution

Put more defaults into docker-compose.

Run the tls container from docker-compose too. If the tls certs happen to be generated already (either from setup.sh or from previous run) it would do nothing.

**Comment by gianarb** [comment]
Can we remove docker-compose at all and use just binaries?

**Comment by mmlb** [comment]
Related to #418
