### ISSUE TITLE
Lets go back to building binaries outside of Docker

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#368]
As stated in #367 I like to build and run the services using docker-compose on my dev machine. Doing any small change to any of the services causes a rebuild of the binary in docker. This is generally slower than just building and COPYing during build but its made worse because the dependencies need to be downloaded each and every time.

## Context

My edit-build-test cycle takes longer than necessary, so does CI.

I know this was added to support multi-arch images, but I think we can do better.

We can wire up a `run` target in the Makefile that has the dependencies properly set so that the binaries are built. This will take care of trying to run the docker-compose but no builds are done yet.

For the multi-arch images we can make use of `sed` to replace "vanilla" binary names with $GOOS & $GOARCH binaries. This would happen in ci or in make so not a big deal imo.

**Comment by gianarb** [comment]
sandbox will copy binaries from the containers across all the architectures to release them as artifacts side to a GitHub release. So just remember to keep the binaris where they are in `/usr/bin` so the automation won't break or require changes 👍

**Comment by thebsdbox** [comment]
I think this can be closed now @gianarb ?

**Comment by mmlb** [comment]
@thebsdbox nope I don't think so, the binaries *for the containers* are still only built in the Dockerfile. I'll likely take inspiration from https://github.com/tinkerbell/boots/pull/122 to do this.

**Comment by mmlb** [comment]
Also, I'm starting on this now :D.

**Comment by gianarb** [comment]
Yayyyy thanks @mmlb
