### ISSUE TITLE
tink-cli should parse template name from the template itself

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#377]
Why do we have a template name cli arg when `name` is a require template field? `tink-cli` should use the name in the template. Doing otherwise can lead to lots of confusion.

**Comment by gianarb** [comment]
@parauliya can you tell us how you want to fix this issue first?
Thanks

**Comment by parauliya** [comment]
> first

Sure @gianarb .
I am thinking of removing the requirement of `name` from the `tink template create` command and for the database I will take that field from the template data.
What do you think

**Comment by gianarb** [comment]
I think it is created and if other commands have the same issue, please remove the flag as well!

**Comment by moadqassem** [comment]
@gianarb Would be cool if you can update the documentation where the template name flag isn't mentioned during the workflow creation. I added an issue to track it. https://github.com/tinkerbell/tink/issues/448. But actually, I find having a `--name` is still useful. If the `--name` was provided then you should override the template with the flag value.

**Comment by gianarb** [comment]
Hey @moadqassem the documentation is based on the last tagged version of the sandbox. It still supports `--name` flag and that's why we didn't update it yet.

The PR you opened to the documentation will be merged as long as other updates as soon as we are ready to bump sandbox! 👍
