### ISSUE TITLE
Migration required running latest Docker image with latest SQL file

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#380]
## Expected Behaviour

Tink-server should not print the following log when running latest Docker image with latest DB schema:
```
tink-server_1  | {"level":"info","ts":1607595392.3107579,"caller":"tink-server/main.go:71","msg":"Your database schema is not up to date. Please apply migrations running tink-server with env var ONLY_MIGRATION set.","service":"github.com/tinkerbell/tink"}
```

## Current Behaviour

Tink-server prints log message above.

## Steps to Reproduce (for bugs)

1. Run https://github.com/tinkerbell/sandbox with image tag `sha-9c52cca5` and respective SQL file: https://github.com/tinkerbell/tink/blob/9c52cca/deploy/db/tinkerbell-init.sql

**Comment by invidian** [comment]
Oh, it seems this causes issues with watching events:
```
$ ./tink-cli events watch
2020/12/10 11:20:57 rpc error: code = Unknown desc = pq: relation "events" does not exist
```

**Comment by thebsdbox** [comment]
This looks like it impacts the events @gauravgahlot ?

**Comment by gianarb** [comment]
I think there is some misuderstanding here

https://github.com/tinkerbell/tink/blob/9c52cca/deploy/db/tinkerbell-init.sql

This file should not be used

**Comment by gianarb** [comment]
https://github.com/tinkerbell/sandbox/pull/30

This PR should make it cristal clear how the process is.

https://github.com/tinkerbell/sandbox/pull/30

And watching the logs from the tink server, migration is not required when the server is up to date.

**Comment by invidian** [comment]
Thanks again for your help @gianarb, you pointed me to the right direction.

I was working on https://github.com/tinkerbell/terraform-provider-tinkerbell/pull/20 and I following changes to the sandbox repo: https://github.com/tinkerbell/terraform-provider-tinkerbell/pull/20/commits/c0a3f5f732482d384664062b671a76aa25a48ad2

After this, everything looks good again! Will close then.
