### ISSUE TITLE
"tink workflow state" does not return error when workflow UUID can't be found

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#381]
## Expected Behaviour
Running `tink workflow state $(uuidgen)` should always return error.

## Current Behaviour

Running the command above exits with 0:
```
0 ✓ (28.1ms) 11:23:44 invidian@dellxps15mateusz ~/repos/kinvolk/tink/cmd/tink-cli (master)$ ./tink-cli workflow state $(uuidgen)
+----------------------+---------------+
| FIELD NAME           | VALUES        |
+----------------------+---------------+
| Workflow ID          |               |
| Workflow Progress    | 0%            |
| Current Task         |               |
| Current Action       |               |
| Current Worker       |               |
| Current Action State | STATE_PENDING |
+----------------------+---------------+
0 ✓ (54.4ms) 11:23:48 invidian@dellxps15mateusz ~/repos/kinvolk/tink/cmd/tink-cli (master)$
```

## Possible Solution

Add validation.

## Steps to Reproduce (for bugs)

1. `tink workflow state $(uuidgen)`
2.
3.
4.

## Context

Tinkerbell version: 9c52cca562bcb70c89228db41ed25a0ef6ca5f52

**Comment by gianarb** [comment]
@thebsdbox I removed the bug label because looking at the code, it is written with that behavior in mind. I don't have enough context to know why, but first, we have to figure out if this is a feature or a bug

**Comment by splaspood** [comment]
In my opinion this is most certainly a bug.   A deleted workflow still has state in the database that could be returned here.   If the intention is to not return data for deleted workflows, then the state command should return an error when looking up a 'nonexistent' workflow.

**Comment by gianarb** [comment]
I think we should leave it there for visibility and troubleshooting purpose
at least for some time. For the same reason kubernetes doesn't delete
resource straight away.

But I am not sure how it works today
