### ISSUE TITLE
Remove facilty params/concept from all of tinkerbell

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#389]
Facility concept is very EM specific and as such should be removed. I'm pretty sure we don't need it as any current use of it would be better served with explicit URLs instead of plugging facility into a hard code string "template".

**Comment by gianarb** [comment]
I had quick look at it and this is a bc break I think, the cert endpoint will break because it requires a facility for example.

So, how do we want to proceed? bc break?

@mmlb

**Comment by jacobweinstock** [comment]
facility has its use but this issue isn't up to date with the code base anymore.
