### ISSUE TITLE
Events are not cleaned up when workflow is removed

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#396]
## Expected Behaviour
Events associated with a workflow should be removed when workflow itself is removed.

## Current Behaviour
`tink workflow events` returns events for workflows, which are not listed by `tink workflow list`.
## Possible Solution
Remove workflow and all associated events inside single transaction to ensure everything is cleaned up.

## Steps to Reproduce (for bugs)

1. Run sample workflow.
2. Run `tink workflow delete` to remove your sample workflow.
3. Run `tink workflow events` to list events for your workflow.

## Context

Orphan events may accumulate over time if one runs large amount of workflows, which will lead to extensive disk usage, slower seek of events etc.

One argument against this might be, that events may be used as sort of audit feature. In such case a different issue would be needed, to periodically remove events older than X days to keep number of rows reasonable.

**Comment by gianarb** [comment]
That's not a concern I have, there is (or if there is not we will have one) a GC cleaning up old events no matters if the workflow is still there or not (they have a TTL almost like the Kubernetes one)

**Comment by invidian** [comment]
Would it make sense to hide events for work flows which had been removed maybe? I was surprised that I removed the workflow and I was still able to find events for it.

**Comment by gianarb** [comment]
> Would it make sense to hide events for workflows which had been removed maybe?

I better understand your perspective here. Now that you know how it works and that there is a TTL attached to the events do you feel confused? Because I prefer to solve this by documenting the event lifecycle more than adding more code

**Comment by invidian** [comment]
>I better understand your perspective here. Now that you know how it works and that there is a TTL attached to the events do you feel confused? Because I prefer to solve this by documenting the event lifecycle more than adding more code

The TTL is time based?

Generally speaking, if this is like this _by design_, then yeah, having it documented would be great and enough for me :+1:

**Comment by gianarb** [comment]
Yes the TTL is time-based and it can be changed in tink-server with an env var, you can find more about this in the actual proposal. https://github.com/tinkerbell/proposals/blob/master/proposals/0012/README.md

Documentation for events is ongoing (I am writing it, so I will be sure to include this conversation!)

**Comment by gianarb** [comment]
I think this was related to event system we dropped #464 . Closing
