### ISSUE TITLE
Worker VM fails to boot

### ISSUE THREAD

**Issue by Cbkhare** [tinkerbell/tink#400]
worker VM fails to boot

## Expected Behaviour
- worker VM should boot
- workflow assigned to the worker should be executed

## Current Behaviour
- worker doesn't boot
- ipxe request is not reaching to the boots container. 

## Steps to Reproduce (for bugs)
1. Create a vagrant setup
2. Create a workflow
3. start worker 

## Your Environment
- Ubuntu

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
* vagrant

* Link to your project or a code example to reproduce issue:
* Master branch in the sandbox

**Comment by Cbkhare** [comment]
![Uploading Screenshot from 2020-12-18 19-31-12.png…]()

**Comment by Cbkhare** [comment]
issue resolve after updating the VirtualBox to the older version. Problem is probably around focal release of Ubuntu.

**Comment by Cbkhare** [comment]
worker vm boot up is failing only for vagrant setup.

**Comment by gianarb** [comment]
It is has to be fixed I suppose right?

**Comment by Cbkhare** [comment]
There was a networking issue on my setup.
