### ISSUE TITLE
Consistent user experience across tink-cli list command -q

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tink#403]
https://github.com/tinkerbell/tink/pull/402

@gauravgahlot I think changes in user experience should be discussed together first, and second, we have to try to be as consistent as possible in the CLI. (we are pretty bad with that)

Can you add the same change you made here for the other resources?

Thanks

**Comment by gauravgahlot** [comment]
Apologies, I should have submitted a proposal first. I'm already in progress to make it consistent across the CLI.

**Comment by gianarb** [comment]
Well, no need for a proposal for that :) but just an issue is fine or even a PR with a bit more time to handle that, anyway, overall the feature is good and needed so thank you for that! We just have to port it to all the other commands so people will have a more friendly experience using the CLI
