### ISSUE TITLE
Evaluating template in workflow replaced << with &lt;<

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#415]
## Expected Behaviour
Workflow properly renders template without replacing any characters.

## Current Behaviour

When template includes sequence like `<<`, it gets replaced into `&lt;<.

## Possible Solution

Use `text/template` instead of `html/template` when rendering workflows.

## Steps to Reproduce (for bugs)

Unit test to reproduce:
```go
func TestRenderTemplateNotHTML(t *testing.T) {
        validTemplate := `
version: "0.1"
name: hello_world_workflow
global_timeout: 600
tasks:
  - name: "hello world<<"
    worker: "{{.device_1}}"
    actions:
    - name: "hello_world"
      image: hello-world
      timeout: 60
`
        templateID := uuid.New().String()
        hwAddress := []byte("{\"device_1\":\"08:00:27:00:00:01\"}")

        result, err := RenderTemplate(templateID, validTemplate, hwAddress)
        if err != nil {
                t.Fatalf("rendering should not fail")
        }

        expected := "hello world<<"

        if !strings.Contains(result, expected) {
                t.Fatalf("Result should contain %q, got \n\n%s", expected, result)
        }
}
```

## Context
https://twitter.com/_invidian/status/1339504259340091392

Found while working on https://github.com/tinkerbell/cluster-api-provider-tink/pull/17.

## Your Environment

Tinkerbell sandbox from version https://github.com/tinkerbell/sandbox/commit/be40a7b371fdab947a413e190cfe99b692651d8e.

**Comment by gianarb** [comment]
I agree with John Arundel https://twitter.com/bitfield/status/1339506837230632960 is not a bug it is a security-conscious decision. 

I am joking thank you for opening this issue

**Comment by invidian** [comment]
Added sample unit test to reproduce. Perhaps one in the code could be more comprehensive.
