### ISSUE TITLE
Allow configuring DNS server for worker machines via DHCP

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#439]
## Expected Behaviour
Hardware DHCP entry should have a dns servers field which should accept one or more DNS resolver, which will be offered as part of DHCP response to the worker nodes.

## Current Behaviour

DNS settings on worker machines must be configured manually, e.g. using userdata.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by gianarb** [comment]
Not sure if it is what I am looking at but boots accept a DNS env var that can be used for something :D probably to configure this. @mmlb do you know more?

Thanks

**Comment by tstromberg** [comment]
This should in fact work. If it doesn't in your experience, please reopen this issue. Thank you!
