### ISSUE TITLE
add init support for centos7

### ISSUE THREAD

**Issue by nathangoulding** [tinkerbell/tink#44]
The setup script is not working on a CentOS 7 machine:

```shell
[root@localhost tink]# ./setup_with_docker_compose.sh
grep: /etc/network/interfaces: No such file or directory
This is network interface
grep: /etc/network/interfaces: No such file or directory
```

It should also have `set -e` to stop execution if there are errors.

**Comment by parauliya** [comment]
This issue has been addressed in PR #62 which is for the issue #49 .
