### ISSUE TITLE
Workflow version needs bump

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#440]
The workflow/template spec effectively changed via #436 but tink's validation wasn't updated and should be. We should also validate that only `""` and `"host"` are accepted.

## Expected Behaviour

Running a workflow template with pid namespace config should fail on older tink deployments. We should support template version 0.2 and only support pid ns in templates >= 0.2.

## Current Behaviour

Pid namespace is not applied on older tink.
There's no validation that only `""` or `"host"` are provided.

**Comment by mmlb** [comment]
I've got the beginnings of some code for this already but can't continue with it for a little while yet.

**Comment by mmlb** [comment]
@thebsdbox bringing to your attention

**Comment by chrisdoherty4** [comment]
Workflows and Templates are now modeled using Kubernetes CRDs. CRDs have their own versioning mechanism so we are unlikely to need an additional versioning scheme on top. Consequently, we're trending towards removal of template versioning.
