### ISSUE TITLE
Template create function appears broken

### ISSUE THREAD

**Issue by thebsdbox** [tinkerbell/tink#445]
## Expected Behaviour

The `-p` flag would read a file, or if no `stdin` happens it exists gracefully..

## Current Behaviour

```
root@ubntu-tmpl:~/debian-workflow/debian# t template create -p ./bullseye.yml
^C
root@ubntu-tmpl:~/debian-workflow/debian# cat ./bullseye.yml | t template create
Created Template:  9ee98590-7c15-11eb-a824-0242ac120005
```
Create will hang if nothing is piped in. 

## Steps to Reproduce (for bugs)

Example is show above.

**Comment by gianarb** [comment]
With the information I got speaking with Dan this is a problem he is currently experiencing with sandbox/master branch.

We have to validate if it is still valid with the newest version of `tink/cli`.
