### ISSUE TITLE
Fix the current documentation for Equinix Metal Setup with Terraform

### ISSUE THREAD

**Issue by moadqassem** [tinkerbell/tink#448]
In the current documentation, the flag `--name` which used to be part of the `tink template create` cmd has been removed in later versions, however the it is still mentioned in the documentation. 
## Expected Behaviour

The `--name` flag should be dropped from the documentation and only mention that the name property is set in the template.yaml file.
## Current Behaviour

Using the `--name` as the documentation proposes gives this error: 
```shell
Error: unknown flag: --name
Usage:
  tink template create [flags]

Flags:
  -h, --help          help for create
  -p, --path string   path to the template file

Global Flags:
  -f, --facility string   used to build grpc and http urls

unknown flag: **--name**
```
## Possible Solution

Fix the documentation by dropping the `--name` flag in https://docs.tinkerbell.org/setup/equinix-metal-terraform/#creating-a-template

## Context

Setting up TinkerBell using Equinix Metal Setup with Terraform

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by gianarb** [comment]
Hello
Thank you for your contribution.

This PR can't be merged now. It first requires a new release of sandbox with the new CLI.

**Comment by moadqassem** [comment]
@gianarb I see. Yeah that makes total sense. We actually had the same issue in the past in regards to documentation for master and other releases. We fixed that by adopting specific documentation per release, where you create a documentation that matches the master and with each release you flush the documentation that the master has to what has been released. I will close the issue 

/close
