### ISSUE TITLE
Change tink-worker when it fails workflow execution. Now it exists with exit-code different than zero

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/tink#458]
https://github.com/tinkerbell/tink/issues/458#issuecomment-797825897

This is a better explanation :D

**Comment by jacobweinstock** [comment]
hmmm.....I don't experience this issue. Here are the versions of the stack that I'm running:
```bash
export OSIE_DOWNLOAD_LINK=https://tinkerbell-oss.s3.amazonaws.com/osie-uploads/osie-v0-n=404,c=c35a5f8,b=master.tar.gz
export TINKERBELL_TINK_SERVER_IMAGE=quay.io/tinkerbell/tink:sha-a41538da
export TINKERBELL_TINK_CLI_IMAGE=quay.io/tinkerbell/tink-cli:sha-a41538da
export TINKERBELL_TINK_BOOTS_IMAGE=quay.io/tinkerbell/boots:sha-b8320d5c
export TINKERBELL_TINK_HEGEL_IMAGE=quay.io/tinkerbell/hegel:sha-c8a68311
export TINKERBELL_TINK_WORKER_IMAGE=quay.io/tinkerbell/tink-worker:sha-a41538da
```

This is the hardware data:
```json
{
    "id": "ce2e62ed-826f-4485-a39f-a82bb74338e3",
    "metadata": {
        "facility": {
            "facility_code": "onprem",
            "plan_slug": "c2.medium.x86",
            "plan_version_slug": ""
        },
        "state": ""
    },
    "network": {
        "interfaces": [
            {
                "dhcp": {
                    "mac": "00:50:56:25:11:0e",
                    "name_servers": [
                        "1.1.1.1",
                        "8.8.8.8"
                    ],
                    "arch": "x86_64",
                    "ip": {
                        "address": "192.168.2.130",
                        "netmask": "255.255.255.0",
                        "gateway": "192.168.2.1"
                    }
                },
                "netboot": {
                    "allow_pxe": true,
                    "allow_workflow": true
                }
            }
        ]
    }
}
```

I don't have any workflows defined and the machine boots into OSIE and the `tink-worker` container runs waiting for a workflow. Once I create a workflow it kicks off right away.

**Comment by moadqassem** [comment]
@gianarb & @jacobweinstock I guess the issue that we are having is kinda different(doesn't match the description). So the problem really is, if you are executing a workflow, and for some reasons the workflow fails(says it failed to pull the image). Now I would expect that, `tink-worker` would still be up and running. What happens is, `tink-worker` simply exits with non zero status, which means non of the future workflows will be executed.

**Comment by jacobweinstock** [comment]
ah yes, I've experienced this before as well. It probably warrants a new GitHub issue. Regardless, I'll comment here on what I think are some potential short and long-term fixes for this.

Short-term:
- PR to add `--restart always` to the [workflow-helper.sh](https://github.com/tinkerbell/osie/blob/6bf665c2fd3906e5429237ce9dc7d735856bd6d4/apps/workflow-helper.sh#L80) script in OSIE
- Add `--restart always` to the file `state/webroot/workflow/workflow-helper.sh` being served by your running Tinkerbell stack

Long-term:
- PR to add `--restart always` to the [workflow-helper.sh](https://github.com/tinkerbell/osie/blob/6bf665c2fd3906e5429237ce9dc7d735856bd6d4/apps/workflow-helper.sh#L80) script in OSIE
- refactor `tink-worker` to never `panic` or `os.Exit`. 
  - log the errors that happened and try whatever failed/errored again
  - create a health endpoint that goes unhealthy whenever an error/failure occurs and try whatever failed/errored again
- have `tink-worker` try to pull/run a container image from the specified private registry and if that fails try the pull/run again without specifying a private registry. this general idea is already captured [here](https://github.com/tinkerbell/tink/issues/303)
  - if `192.168.1.2/myimage` fails then `myimage`

**Comment by gianarb** [comment]
Let me update the topic of this issue because I didn't write it properly.

Anyway, @jacobweinstock we are in the position to do the right thing. Not looking for shortcuts here. [osie](/tinkerbell/osie) can implement the `--restart always` if it wants. But we have to make this solution working with any other implementation of it.

This means that we need to fix `tink-worker`. I am not sure the solution if are proposing is desired or inline with the scenario @moadqassem proposed.

Fallback to ANOTHER image is a security issue and I think undesirable. The issue you linked is different. We do not have a comfortable or well-defined way to authenticate but it is possible. So I think the issue you linked can be solved with more documentation and in any case, change the image runtime is not something we should do I think.

To get back to the object of this issue:

> tink-worker simply exits with non zero status, which means non of the future workflows will be executed.

We should make tink-worker a long-running process that never exits, if a workflow fails it reports the ACTION as failed and it terminates the workflow execution waiting for the next one to come.

**Comment by moadqassem** [comment]
@gianarb & @jacobweinstock `--restart` in the shell script might work for now to fix the issue, however it is a bit inconvenient as `tink-worker` should be actually treated as an agent more than being treated as an execution block where it is called only when a workflow is created. Also, restarting the container would give you a lot of noise logs that are not needed. In my opinion what should bring up and take care of the `tink-worker` lifecycle is the `tink-server` instead of introducing this deep level of modularity, where the link between the agent(`tink-worker`) and the control plane(`provisioner`) is done only via creating workflows. The `provisioner` should be able to track the `tink-worker` (via heath check maybe?) and if it is not there it should be able to run a cmd on the worker to bring it again. Those are my thoughts but you probably guys know better ¯\_(ツ)_/¯

**Comment by gianarb** [comment]
> Those are my thoughts but you probably guys know better ¯_(ツ)_/¯

I agree, with almost everything. Let's leave the health check part out from this discussion because it is an interesting and complicated problem by its own 👍

**Comment by jacobweinstock** [comment]
> @gianarb & @jacobweinstock `--restart` in the shell script might work for now to fix the issue, however it is a bit inconvenient as `tink-worker` should be actually treated as an agent more than being treated as an execution block where it is called only when a workflow is created. Also, restarting the container would give you a lot of noise logs that are not needed. In my opinion what should bring up and take care of the `tink-worker` lifecycle is the `tink-server` instead of introducing this deep level of modularity, where the link between the agent(`tink-worker`) and the control plane(`provisioner`) is done only via creating workflows. The `provisioner` should be able to track the `tink-worker` (via heath check maybe?) and if it is not there it should be able to run a cmd on the worker to bring it again. Those are my thoughts but you probably guys know better ¯_(ツ)_/¯

sounds like you want a worker to be a node in a Kubernetes cluster ;)

**Comment by jacobweinstock** [comment]
> Let me update the topic of this issue because I didn't write it properly.
> 
> Anyway, @jacobweinstock we are in the position to do the right thing. Not looking for shortcuts here. [osie](/tinkerbell/osie) can implement the `--restart always` if we want (I think we should). But we have to make this solution working with any other OSIE implementation.
> 
> To facilitate that we need to fix `tink-worker`. I am not sure the solution you are proposing is desired or inline with the scenario @moadqassem proposed.
> 
> Fallback to ANOTHER image is a security issue and I think undesirable. The issue you linked is different. We do not have a comfortable or well-defined way to authenticate but it is possible (you have to pass credentials someway to OSIE). So I think the issue you linked can be solved with more documentation and in any case, change the image runtime is not something we should do I think. (moving from a private registry specified in the workflow to another registry, in practice means to change the image potentially)
> 
> > tink-worker simply exits with non zero status, which means non of the future workflows will be executed.
> 
> We should make tink-worker a long-running process that "never" exits, if a workflow fails it reports the ACTION as failed and it terminates the workflow execution waiting for the next one to come.

You are right. The fallback idea isn't a good one. The idea should just be to support public registries like https://github.com/tinkerbell/tink/issues/303 states. 

Sounds like we are in alignment though on "_refactor tink-worker to never panic or os.Exit._" and "_We should make tink-worker a long-running process that "never" exits,"_

**Comment by gianarb** [comment]
Perfect!d )
