### ISSUE TITLE
Getting Started Experience

### ISSUE THREAD

**Issue by vishal-biyani** [tinkerbell/tink#49]
The current getting started UX involves a few steps. Instead, it should be as simple as running a single script which encapsulates all other stuff. The script can take inputs from users if needed.

```
curl https://raw.githubusercontent.com/tinkerbell/tink/master/setup.sh | bash
```

**Comment by alexellis** [comment]
@vishal-biyani what's the next step after running this script? What hardware would you see it being compatible on? And why would this be run instead of the terraform at: https://tinkerbell.org/setup ?
