### ISSUE TITLE
Website is out of date

### ISSUE THREAD

**Issue by deitch** [tinkerbell/tink#50]
The website http://tinkerbell.org only has two pages, and missing a lot of information that is in the `docs/` in this repo. It is ok to have _much_ more detailed docs on the Website, but it either should clearly have no real guides and point to the right guide in the repo, or should have a good but very simple "getting started" guide. Even better if it aligns with #49

**Comment by mrmrcoleman** [comment]
@deitch Closed as this is captured elsewhere.
