### ISSUE TITLE
Is the compose file to build it or to run it?

### ISSUE THREAD

**Issue by deitch** [tinkerbell/tink#51]
There is a compose file in this repo, but it isn't completely clear if it is to _build_ tinkerbell or _run_ it. If it is to run it, there are dependencies on git and git-lfs, which make it difficult to "just run".

**Comment by parauliya** [comment]
Hi @deitch , 
Please have a look at pull request #62 . There is compose file in this pull request which is the updated one. This compose file contain few containers which will be build instanlty and run and for the remaining containers it will just fetch the image from `quay.io` and start the container. Hope this helps.

**Comment by deitch** [comment]
Looks like it addresses it. I will leave this open until that is merged in, reread the docs and see if we can close it.

**Comment by gauravgahlot** [comment]
Closing as #62 is merged.
