### ISSUE TITLE
Improve Go Report Card compatibility

### ISSUE THREAD

**Issue by nicklasfrahm** [tinkerbell/tink#512]
Currently, the CI setup of this repository does not catch all the issues and warnings that [Go Report Card](https://goreportcard.com/report/github.com/tinkerbell/tink) catches. To solve this, we should make the CI tests more strict to:

- [ ] consider cyclomatic complexity warnings as errors
- [ ] consider linter warnings as errors
- [ ] add Go Report card label to README.md

**Comment by tstromberg** [comment]
I think this sounds like a great idea. Is anyone up to implement it?
