### ISSUE TITLE
`test/` directory purpose?

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#526]
Hello. Does anyone have any details on the `test/` directory? I don't see a Make target for it. `test/e2e_test.go` seems to possibly be an entry point for running the code, but it's all commented out. I don't see any CI that runs it either. Is it still in use somehow? If so, how do we run it? Is it maybe something that can be removed? or moved to the sandbox?

Tagging a few folks whose names I see as committers to those files to see if they possibly have some insight. @parauliya @mmlb @kqdeng 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by mmlb** [comment]
Looks like old E2E tests that were commented instead of deleted. I'd say we rectify that.

**Comment by mmlb** [comment]
The vagrant based tests used to be here too, according to git history, but those are gone now.
