### ISSUE TITLE
clarifications for setup page - what is inputenv?

### ISSUE THREAD

**Issue by deitch** [tinkerbell/tink#53]
The [setup page](https://github.com/tinkerbell/tink/blob/master/docs/setup.md) has no info under what to provide in `inputenv`. The file only has a few elements, but some could be read in multiple ways:

* what is host IP vs nginx IP?
* Why are there two?
* Do these need to be on the same network?
* I assume broad_ip means broadcast, but it isn’t self-evident?
* What is the cidr for? Is it the netmask for the above (coming back to above question, “do they need to be on the same network”)?

**Comment by gauravgahlot** [comment]
@deitch I'm hoping the new setup has filled the gaps now. However, please let me know if there is something that is still not clear. We close this issue otherwise.
