### ISSUE TITLE
What is OSIE for? It isn't in some of the docs

### ISSUE THREAD

**Issue by deitch** [tinkerbell/tink#54]
Where does OSIE fit in? It isn’t in the architecture diagram [here](https://github.com/tinkerbell/tink/blob/master/docs/architecture.md) and isn’t listed as one of the “major components”, so how does it fit in?

**Comment by gianarb** [comment]
Thank you for opening this issue. Here we are! more will come I am sure
https://tinkerbell.org/docs/services/osie/

Closing for now!
