### ISSUE TITLE
Do we need git-lfs?

### ISSUE THREAD

**Issue by deitch** [tinkerbell/tink#55]
What do we use git-lfs for? Based on the `.gitattributes` file in boots [here](https://github.com/tinkerbell/boots/blob/master/.gitattributes), it looks like 

* 3 `.efi` files
* 1 `.kpxe` file
* 1 `.go` file; how large could a go file be and what is in it?

More importantly, do these need to be in lfs? Are they actually versioned source, or just generated binaries that we use, and possibly could move to a saner store for large data that itself does not require versioning, or at least not subject to PR-style changes and tracking like normal source code?

Yes, I am thinking about OCI image repositories which do quite well with things like this, but either way, this creates complexity in git and a dependency on git and git+lfs to start it.

**Comment by deitch** [comment]
In a direct message conversation, I received some answers from @mmlb .


### efi and kpxe files

The `.efi` and `.kpxe` files are built artifacts, primarily stored here in git-lfs to avoid having to regenerate for CI. 

It still is unclear to me if these artifacts are needed _solely_ for CI, or do we need them _also_ to just run tinkerbell stand-alone?

### go file

> the go file is a go-bindata generated of all the ipxe binaries

It seems odd to have a `.go` file generated and not in normal version control. Does the data need to be built right into the `.go` file? Or can it read it runtime?

**Comment by mrmrcoleman** [comment]
@mmlb Did we decide to keep GitLFS?

**Comment by mmlb** [comment]
> It still is unclear to me if these artifacts are needed _solely_ for CI, or do we need them _also_ to just run tinkerbell stand-alone?'

They are used at run time, these are the iPXE files we serve up to the nics for pxe-boot.

> > the go file is a go-bindata generated of all the ipxe binaries
> 
> It seems odd to have a `.go` file generated and not in normal version control. Does the data need to be built right into the `.go` file? Or can it read it runtime?

The .go file is in normal version control. It's just generated from other source controlled files (the git-lfs'd ipxe files) instead of an engineer's head ;). This is done to main go-get ability and reproducible builds.

**Comment by mmlb** [comment]
> @mmlb Did we decide to keep GitLFS?
Yes we want to keep git-lfs. Without it the git repo will bloat the full binary file size for any change in the binaries; version updates, rebuilds, config updates, ...

**Comment by deitch** [comment]
Hey @mmlb I don’t think anyone was suggesting that we put the large files in git directly. But requiring git and gitlfs for runtime (not just buildtime) will restrict tinkerbell only to developers, keeping out the broader circle of operators. We are comfortable with git and lfs, but do we want to restrict our target audience? What tools are they using to distribute large binaries?

**Comment by nathangoulding** [comment]
> Hey @mmlb I don’t think anyone was suggesting that we put the large files in git directly. But requiring git and gitlfs for runtime (not just buildtime) will restrict tinkerbell only to developers, keeping out the broader circle of operators. We are comfortable with git and lfs, but do we want to restrict our target audience? What tools are they using to distribute large binaries?

They are used at runtime, not fetched at runtime. If you set up the provisioner you can see how it works.

**Comment by deitch** [comment]
> They are used at runtime, not fetched at runtime

Good point. I should have been a bit clearer. 

It still requires them to use git to set it up. I agree, operators _are_ getting better at git and dev-style tools, but it still isn't the world they run in.

**Comment by mmlb** [comment]
I'm not sure I see the issue here. Git and Git LFS only come into play if some one is trying to build boots. Having git and git-lfs installed for that seems fine? Operators will use the container images right?

**Comment by deitch** [comment]
That was what I didn't get. If I just want to install and run it - not as a developer trying to change it, but as someone who just wants to follow a README and start it so I can manage some metal - do I need git or not? I had thought I did. If not, the questions go away.

**Comment by mmlb** [comment]
Ah nope, its just for building of boots. Using it should be directly from the container image.

**Comment by deitch** [comment]
Cool, thanks. I haven't had a chance to do a fresh run in a few weeks. I will give it another run next week, and if all is clear, will close this out.

**Comment by mmlb** [comment]
:+1:

**Comment by mrmrcoleman** [comment]
Can this issue be closed @deitch ?

**Comment by deitch** [comment]
> Can this issue be closed @deitch ?

I have no idea. I tried following the "deploy on Packet" instructions, and ended up giving up long before I was able to see how the artifacts are downloaded. Once you switch the network type, you get locked out after reboot, and no IP for the iPXE. I wasn't quite ready to dig into code and figure it out.

If it is important to close it, go ahead.

**Comment by mmlb** [comment]
@mrmrcoleman I think we can close this out. I think this issue is too open ended. We use git-lfs in 2 ways:
1. In source code repos, so only pertinent for developers wanting to build the individual services
2. In our packet-images repo to deliver images. OSIE does *not* require git-lfs images though and would be just fine loading a normal git repo.

@deitch you brought up OCI image repositories which may make sense, but that discussion should be in a new issue more tightly defined.

**Comment by mrmrcoleman** [comment]
Thanks @mmlb
