### ISSUE TITLE
Mergify configuration probably needs updates

### ISSUE THREAD

**Issue by nshalman** [tinkerbell/tink#568]
See https://github.com/tinkerbell/tink/pull/567/checks?check_run_id=4436215781

> The Mergify configuration is invalid
> The configuration uses the deprecated strict mode of the merge action.
> A brownout is planned for the whole December 6th, 2021 day.
> This option will be removed on January 10th, 2022.
> For more information: https://blog.mergify.com/strict-mode-deprecation/
> 
> smart+fastpath is invalid for dictionary value @ pull_request_rules → item 0 → actions → merge → strict
> 

![image](https://user-images.githubusercontent.com/20391/144923469-829929a6-bee3-40c7-838e-fe9e3cdfc858.png)

**Comment by jacobweinstock** [comment]
Hey @nshalman, is this still an issue? I remember you and @mmlb discussing this a bit back.

**Comment by nshalman** [comment]
> Hey @nshalman, is this still an issue? I remember you and @mmlb discussing this a bit back.

Based on the Message from Mergify, If we don't fix things by January 10, we will have a breakage.

**Comment by mmlb** [comment]
Done for all the repos as part of https://github.com/orgs/tinkerbell/projects/10
