### ISSUE TITLE
update docs to use latest.tar.gz

### ISSUE THREAD

**Issue by nathangoulding** [tinkerbell/tink#57]
On merge to master, we are uploading the latest osie here:

https://tinkerbell-oss.s3.amazonaws.com/osie-uploads/latest.tar.gz

We should update our docs and setup scripts to use this instead of pinning to a particular version.

**Comment by parauliya** [comment]
Hi @nathangoulding , We have updated this link in our setup script. But we are not aware of where to put this link in our docs because we have not added the old/previous link of osie.tar.gz in our docs anywhere. Could you please suggest where to add this link in docs?
