### ISSUE TITLE
Make lint, vet and fmtcheck part of Makefile and part of CI run

### ISSUE THREAD

**Issue by deitch** [tinkerbell/tink#58]
We definitely should be running golint as part of our CI and fail it otherwise. It should be in the Makefile, so anyone can run it.

We also should be running `go vet`.

Finally, we should be running fmt check. We should *not* update the files as part of fmt check (as in `gofmt -w -s <file>`) but should be checking it. It usually is useful to have a `Makefile` target called `fmtcheck` that does the above and is executed as part of CI, and also a separate `fmt` target that fixes the files. This makes it easy for someone running it locally to fmt all files in a single command, but also for CI to check the status.

**Comment by deitch** [comment]
See the issue raised first by @alexellis #56

**Comment by invidian** [comment]
Perhaps you should consider using https://github.com/golangci/golangci-lint, which provides more linters, allows to nicely configure them etc?
