### ISSUE TITLE
Remove WorkflowData APIs 

### ISSUE THREAD

**Issue by micahhausler** [tinkerbell/tink#597]
Generated from discussion today in the community meeting, but it sounds like the `GetWorkflowData`/`UpdateWorkflowData` APIs are no longer needed.

I'm happy to submit a PR removing out these APIs. Is there any consideration to be made about gracefully keeping them? The worker currently calls these APIs, and so workers/worker images would need to be updated before switching over.

CC @nshalman @mmlb @jacobweinstock

**Comment by mmlb** [comment]
Its not that they aren't needed any more, its more like they aren't exercised and have rotted a bit. The use case is multi-machine workflows and needing to shuffle data/state between them. There isn't really a use for them within a single machine workflow as data can be persisted in a bind mounted dir in tmpfs somewhere.

If they're getting in the way of something then I think its fine to drop, but what I think I'd *really* love to see is an example multi-machine workflow that would require it. PBnJ is the most obvious use of multi-machine workflows but that is hard to make use of in both the vagrant and tf sandbox examples.

**Comment by jacobweinstock** [comment]
close by https://github.com/tinkerbell/tink/issues/597
