### ISSUE TITLE
unify hardware/target data model

### ISSUE THREAD

**Issue by nathangoulding** [tinkerbell/tink#60]
We need to unify the hardware and target data model, and standardize on the changes that @kdeng3849 introduced to switch to the new, easier to comprehend model. This should also remove cacher as a dependency.

**Comment by gauravgahlot** [comment]
Ref proposal [RFC #1 Merge Hardware and Target models](https://github.com/tinkerbell/tink/wiki/RFC-%231---Merge-Hardware-and-Target-models)
