### ISSUE TITLE
Rethink external runtime dependencies in unit tests

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#608]
The unit test code [here](https://github.com/tinkerbell/tink/blob/453f0fdac80c2db0a19d207e3486dca167743099/db/db_test.go#L24) creates docker containers for use in unit tests. This feels inappropriate for unit tests. Also the way it's written, all tests that call this function will get their own postgres container. As it currently stands, i have seen up to 4 containers running at a single time. This also feels inappropriate.

I would argue that unit tests should not require a container runtime to be installed. They should strive to only require Go. 

I think that for functional or integration testing spinning up containers is acceptable. Maybe this code can be isolated to only be used for functional/integration testing.

Curious what others think?

**Comment by gauravgahlot** [comment]
I remember writing those tests and I had similar concern. However, it was helpful testing the event system I wrote for Tink, and so it was acceptable at that point. But as I look at it now, I find it confusing and overcomplicated. 

I believe we should rather define better abstractions and as you rightly said this code can be isolate for integration tests.

**Comment by chrisdoherty4** [comment]
> I think that for functional or integration testing spinning up containers is acceptable. Maybe this code can be isolated to only be used for functional/integration testing.

Yes.

Unpopular opinion (possibly): Unit tests should also, ideally, run in 10s of ms (sub 100ms) and containers typically take more than .5s to launch.

**Comment by jacobweinstock** [comment]
Closed by https://github.com/tinkerbell/tink/pull/654
