### ISSUE TITLE
quay.io/tinkerbell/tink-controller not publicly available

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#629]
It appears that while in CI we are creating and pushing a tink-controller container image, it doesn't appear to be available publicly.
```bash
$ docker pull quay.io/tinkerbell/tink-controller
Using default tag: latest
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

## Possible Solution

We might just need to check a button in quay.io to make it public?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by displague** [comment]
![image](https://user-images.githubusercontent.com/317653/174187216-f76825d1-ffb8-4510-b3f7-829c56c457dd.png)

**Comment by displague** [comment]
I toggled the setting for this repo:

> This Repository is currently public and is visible to all users, and may be pulled by all users.

**Comment by displague** [comment]
I toggled the setting for this repo:

> This Repository is currently public and is visible to all users, and may be pulled by all users.
