### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/tink#634]
Discussion issue for the 0.7 release.

**Comment by chrisdoherty4** [comment]
@jacobweinstock @micahhausler @mmlb @displague 

Is there anything stopping us from creating a 0.7 release?

**Comment by jacobweinstock** [comment]
I don't believe so. Let's do it! I think @mmlb or @micahhausler (as maintainers) will need to run the release.

**Comment by DavidSpek** [comment]
Would it be possible to update the CI so the images are tagged with the version [here](https://github.com/tinkerbell/tink/blob/main/.github/workflows/ci.yaml#L141). It seems like most (if not all) the other tinkerbell components tag the images with the release versions.

**Comment by displague** [comment]
I created a milestone from all the merges and the (fixed issues according to the merged PRs) https://github.com/tinkerbell/tink/milestone/1?closed=1. This should help with filtering out the issues addressed (since the GH generated changelog does not cover that).

**Comment by displague** [comment]
There may have been other issues closed between 0.6 and 0.7 which were not indicated by PR. 

https://github.com/tinkerbell/tink/blob/main/RELEASING.md covers the release process.

**Comment by mmlb** [comment]
Getting 0.7 out the door sgtm. I've got a lot of catching up to do this week but would like to see it happen by EoW!

**Comment by displague** [comment]
@jacobweinstock added #635 to the milestone

**Comment by chrisdoherty4** [comment]
#635 has been merged. I think we just need a tag assuming everyone is content?

**Comment by chrisdoherty4** [comment]
https://github.com/tinkerbell/tink/releases/tag/v0.7.0
