### ISSUE TITLE
Move interfaces in hardware spec from slice to map

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#636]
Currently the hardware spec contains a slice that holds [interfaces](https://github.com/tinkerbell/tink/blob/a0e9350205d4d5bd0eed72e5a6ec0e5ee12a965c/pkg/apis/core/v1alpha1/hardware_types.go#L54). Duplicate elements are allowed. Clients generally must check for multiple records when searching by things like MAC or IP address (ref [here](https://github.com/tinkerbell/boots/blob/71430bc7b775aa96e88d758ead7f3025c03fc6cb/client/kubernetes/hardware_finder.go#L89)).

With MAC addresses being unique, I think moving to a map of interfaces instead of a slice might be something to consider. This would simplify client code and be a natural way to eliminate duplicate records. Also, clients are generally using a Kubernetes [`.List`](https://github.com/tinkerbell/boots/blob/71430bc7b775aa96e88d758ead7f3025c03fc6cb/client/kubernetes/hardware_finder.go#L92) function to get hardware objects and a map could potentially allow for the use of a `.Get` instead. There might event be some performance improvements when searching through a large number of hardware objects.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by chrisdoherty4** [comment]
I think we need a broader discussion on what the Hardware type should look like, holistically, and head toward that. This seems like a component of that discussion.

**Comment by chrisdoherty4** [comment]
I think this has been dealt with in the v1alpha2 API. Its taking some time to become available but it will address this.
