### ISSUE TITLE
QUESTION: How/Where to start with tinkerbell in 2022?

### ISSUE THREAD

**Issue by blackliner** [tinkerbell/tink#649]
Coming from @gianarb 's appearance on [episode 142 of the Kubernetes podcast](https://kubernetespodcast.com/episode/142-tinkerbell/), I wanted to start looking into tinkerbell. Both professional (we might start with our on-premise efforts, and want to keep the GitOps/IaC culture) as well as personal (usual homelabism).

I tried to make sense out the official documentation, but it somehow lacks in-depth explanation or actual documentation of the components involved (what are all the possible entries for templates, workflows, and hardware specs?). 

Don't get me wrong, everyone hates to write docu, but taking in all the available information, it's really unclear what the state of the project is right now:
- Is it available as a standalone set of binaries, as hinted mostly by https://docs.tinkerbell.org/, where for example [this guide](https://docs.tinkerbell.org/deploying-operating-systems/examples-ubuntu/) mentions a template written in the old(?) way?
- Is it meant to run inside a cluster, as the sandbox [repo suggests](https://github.com/tinkerbell/sandbox/blob/main/deploy/stack/compose/manifests/hardware.yaml) with some k8s yaml specs? Or is this just this type of docker-compose related deployment?
- The [documentation for hardware](https://docs.tinkerbell.org/hardware-data/) is suddenly specifying everything in json (I know its the "same" as yaml), contributing to my overall confusion 🙈 

What I would like to be able to do is to setup a separate (standalone) node (VM or not) to host all of tinkerbells services.
- What is the (2022) state of the art how to integrate tinkerbell? Inside k3s/k8s/microk8s? Standalone? In docker containers? Something else?
- What is the recommended approach to get into tinkerbell? I am missing a trivial example, the [docker-compose.yaml](https://github.com/tinkerbell/sandbox/blob/main/deploy/stack/compose/docker-compose.yml) does A LOT of stuff, even running a k3s cluster. Same story for the [helm called folder but its actually a full blown k3d deployment](https://github.com/tinkerbell/sandbox/tree/main/deploy/stack/helm)
- What are the most up to date documentations and tutorials?

Thanks!

**Comment by jacobweinstock** [comment]
Hey @blackliner, thanks for checking out Tinkerbell! We definitely have a need to update our docs, apologies.  We recently did a [big push](https://github.com/orgs/tinkerbell/projects/14) to update docs and our [sandbox repo](https://github.com/tinkerbell/sandbox) but as you've noted we still don't have them all up to date. Let me try to answer and/or direct you to answers to the questions you have posed.

1. **Question:** _Is it available as a standalone set of binaries, as hinted mostly by https://docs.tinkerbell.org/, where for example [this guide](https://docs.tinkerbell.org/deploying-operating-systems/examples-ubuntu/) mentions a template written in the old(?) way?_
**Answer:** We don't directly make available the binaries for all [Tinkerbell services](https://docs.tinkerbell.org/). We do have container images for each service available. They can be pulled from `quay.io`. See [here](https://quay.io/organization/tinkerbell). Apologies, I'm not following how binaries and templates relate here. The template examples on tinkerbell.org are still very relevant as they are used in the template CRD spec. Please see [here](https://github.com/tinkerbell/tink/blob/main/config/crd/examples/template.yaml) for an example.

2. **Question:** _Is it meant to run inside a cluster, as the sandbox [repo suggests](https://github.com/tinkerbell/sandbox/blob/main/deploy/stack/compose/manifests/hardware.yaml) with some k8s yaml specs? Or is this just this type of docker-compose related deployment?_
**Answer:** The Tinkerbell stack can be run in a Kubernetes cluster, yes. It can also be run via docker compose, as you've linked to. The sandbox repo has a quick starts section that shows a few different ways to bring up the stack.
Regardless of which way to bring the stack up, the recommended way to interact with Tinkerbell is through `kubectl` and our 3 main CRDs (hardware, template, workflow). I would recommend the ["Next Steps"](https://github.com/tinkerbell/sandbox#next-steps) section of the [sandbox](https://github.com/tinkerbell/sandbox) repo's readme.  Also, full spec details for the CRDs can be found [here](https://doc.crds.dev/github.com/tinkerbell/tink@v0.8.0). And, example yamls can be found [here](https://github.com/tinkerbell/tink/tree/main/config/crd/examples).

3. **Question:** _What is the (2022) state of the art how to integrate tinkerbell? Inside k3s/k8s/microk8s? Standalone? In docker containers? Something else?_
**Answer:** This really depends on your use case, environment, team, etc. I would recommend using `helm` in an existing Kubernetes cluster as a start. The sandbox repo quick start for helm links to an examples, as you've seen.

4. **Question:** _What is the recommended approach to get into tinkerbell? I am missing a trivial example, the [docker-compose.yaml](https://github.com/tinkerbell/sandbox/blob/main/deploy/stack/compose/docker-compose.yml) does A LOT of stuff, even running a k3s cluster. Same story for the [helm called folder but its actually a full blown k3d deployment](https://github.com/tinkerbell/sandbox/tree/main/deploy/stack/helm)_
**Answer:** Apologies, I don't know if I understand what you mean by "approach to get into tinkerbell". If you mean, after deploying the Tinkerbell stack how do you start interacting with it then I would recommend the ["Next Steps"](https://github.com/tinkerbell/sandbox#next-steps) section of the [sandbox](https://github.com/tinkerbell/sandbox) repo's readme and the Ubuntu example OS provisioning guide [here](https://docs.tinkerbell.org/deploying-operating-systems/examples-ubuntu/).

5. **Question:** _What are the most up to date documentations and tutorials?_
**Answer:** The sandbox repo's [quick starts](https://github.com/tinkerbell/sandbox#quick-starts) are the most up-to-date for deploying the stack. The docs for "Deploying Operating Systems" on https://tinkerbell.org would be the most up-to-date for using Tinkerbell to provision machines (while these are the most up-to-date, they definitely don't capture the Kubernetes interaction well). I'd also recommend the helm chart repo docs [here](https://github.com/tinkerbell/charts/tree/main/tinkerbell/stack).

Just FYI, we have a [community slack channel](https://tinkerbell.org/community/contact/) in the CNCF's official slack workspace. If that's a helpful/preferred medium, we can discuss there too, or answer questions, troubleshoot issues, etc. 

Very happy that Tinkerbell has piqued your interest and I hope we can help you solve some of your provisioning challenges!

**Comment by chrisdoherty4** [comment]
Most, if not all, questions have been answered. I'm closing the issue but feel free to continue the discussion.
