### ISSUE TITLE
Remove deprecated Watch APIs

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/tink#653]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
close with https://github.com/tinkerbell/tink/pull/654
