### ISSUE TITLE
Document how to get "tink" executable and how to configure it

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#67]
I managed to get it using `go get github.com/tinkerbell/tink`.

**Comment by thebsdbox** [comment]
The `tink` binary is already available within container images as distributed through the example workflow. An additional Issue https://github.com/tinkerbell/tink/issues/73 also documents the creation of the binary which may impact the documentation. 

Additionally the `docker-compose` file is used to start all of the `tink` binaries inside of docker containers. (https://github.com/tinkerbell/tink/blob/master/deploy/docker-compose.yml).

**Comment by gianarb** [comment]
I am gonna close this for now.
We are working on a release process that includes binaries ready to be consumed and the setup.sh script + docker-compose are for now a good way to figure out the installation process. Not ideal but we are working hard to get to something more portable and that is not docker-compose based.
