### ISSUE TITLE
Add ability to reboot the machine after workflow is finished

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#71]
For workflows, which provision the OS, it would be nice if the workflow itself could reboot the machine, after it's done, so the machine can boot itself into target OS, so the upper orchestration system (e.g. person who monitors provisioning process, some kind of logic which use IPMI etc.) don't need to care about that.

Things to consider:
- worker can be part of multiple workflows. Perhaps reboot should only happen when all workflows are successfully finished.
- perhaps workflow could indicate, that after it's finished, the reboot is needed e.g. by setting `reboot` parameter to `true`.
- the action or task can't trigger a reboot by itself, as this will shut down the worker and it won't be able to report that reboot task succeeded

**Comment by rgl** [comment]
it seems that we now have a documented way to do a reboot from an action at https://docs.tinkerbell.org/actions/action-architecture/#namespace:

> When an action attempts to do these steps in a container in its own namespace, nothing will occur as PID 1 is usually the process in the action container. To allow the expected behaviour an action can use pid: host in its configuration, this will mean that the action processes will be amongst all of the processes on the host itself (including the "real" PID 1). With the action in the host process ID namespace both a reboot or kexec will be able to work as expected.

It this issue about improving on that?

**Comment by thebsdbox** [comment]
This is fixed in tink-worker. This can probably be closed! 😀

**Comment by rgl** [comment]
@thebsdbox, by fixed, you mean using an action with `pid: host`?

having a docs example on how to reboot from a workflow would also be really nice :-)

**Comment by rgl** [comment]
Creating a file named `/worker/reboot` does not work:

![Screenshot_rpi-tinkerbell-vagrant_bios_worker_2021-05-26_09:12:14](https://user-images.githubusercontent.com/43356/119626012-b1f88b80-be02-11eb-9ae0-652e5153f646.png)

**Comment by thebsdbox** [comment]
Ah this needs hook.. hook has the logic to watch for the reboot.

**Comment by double-p** [comment]
Built a docker image as per the example @rgl mentioned here already to no avail:

The "touch" is going nowhere and thus the rebootWatch() never fires.

A manual touch in the getty container to "/run/worker/reboot" works, so the watch is active. Just looks the volume mapping is wrong? (/worker:/worker)

**Comment by yeahdongcn** [comment]
```yaml
  - name: "reboot into Windows"
    image: reboot:latest
    timeout: 90
    volumes:
    - /worker:/worker
```

I encountered the same issue in rebooting into Windows, the action failed (STATE_FAILED). Is there any place I can lookup for the error message?

**Comment by yeahdongcn** [comment]
> ```yaml
>   - name: "reboot into Windows"
>     image: reboot:latest
>     timeout: 90
>     volumes:
>     - /worker:/worker
> ```
> 
> I encountered the same issue in rebooting into Windows, the action failed (STATE_FAILED). Is there any place I can lookup for the error message?

It turns out the [document](https://docs.tinkerbell.org/deploying-operating-systems/examples-win/) is incorrect. I just sent out a [PR](https://github.com/tinkerbell/tinkerbell-docs/pull/162) to fix it.

**Comment by chrisdoherty4** [comment]
We intend on drawing up a proposal for embedding restart capabilities into workflows so we don't need to rely on actions. This will compliment a want to see workflows consistently transition to an end state which doesn't happen if the restart beats the restart actions update currently.

**Comment by chrisdoherty4** [comment]
https://github.com/tinkerbell/roadmap/issues/29 will see this come to fruition.

**Comment by jacobweinstock** [comment]
While tinkerbell/roadmap#29 will add builtin capabilities for rebooting, https://github.com/jacobweinstock/waitdaemon can achieve this from an action and still allow the Workflow to report successful.

I'm going to close this. If https://github.com/jacobweinstock/waitdaemon is not an acceptable solution please watch tinkerbell/roadmap#29.
