### ISSUE TITLE
Provide release binary of tink CLI

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#73]
A statically-linked release binary should be made available of the tink CLI. Users shouldn't have to download go to build the CLI, or wonder where to get it from. I couldn't find docs explaining where to find it. There also are no release tags of tink, but there should be, even if the tag is 0.1.0

For an example, see how we do this with arkade or inlets

Build config for Travis/Make:

https://github.com/alexellis/arkade/blob/master/.travis.yml
https://github.com/alexellis/arkade/blob/master/Makefile

Install script:

https://github.com/alexellis/arkade/blob/master/get.sh

**Comment by alexellis** [comment]
Ref: #74

**Comment by alexellis** [comment]
No external tools like goreleaser are strictly needed. Go supports cross-compilation with a couple of flags. See the Makefile example above for instance.

At a minimum the CLI should have a Linux `x86_64` and MacOS option.

**Comment by invidian** [comment]
There is also https://github.com/tinkerbell/boots/issues/4. Perhaps one solution should be picked for all binaries.

I personally like Goreleaser, as it automates building and uploading artifacts to GitHub, making GitHub releases really easy.

**Comment by alexellis** [comment]
In my opinion a Makefile would suffice, goreleaser is a popular, but complex tool.

Bumping this up. @parauliya @gauravgahlot is there an update on this? For instance, after running the setup script, it would be ideal to be able to run "tink" without exec'ing into a container.

**Comment by gianarb** [comment]
We decided to release not every single project for now, but the entire stack, at the end the services are strictly connected and the project evolves quickly at this stage, it is very time-consuming to look at each project in isolation.

Binaryies are here: https://github.com/tinkerbell/sandbox/releases

I will close this issue for now because it won't be implemented soon
