### ISSUE TITLE
Configurable top-level directories

### ISSUE THREAD

**Issue by mmlb** [tinkerbell/tink#81]
We should allow users to tailor where our directories / files get put down. Not necessarily too fine grained, I think supporting $PREFIX or something along those lines in setup.sh would be fine.

**Comment by gianarb** [comment]
@mmlb is this not enough?

https://github.com/tinkerbell/tink/blob/master/setup.sh#L20

**Comment by mmlb** [comment]
@gianarb yep that looks good. We'd want to allow it to be specified in the env to close this issue out.

**Comment by gianarb** [comment]
Looking at the code it already works that way

**Comment by mmlb** [comment]
> Looking at the code it already works that way

Not really right? Looking at the code on https://github.com/tinkerbell/tink/blob/master/setup.sh#L20:

```sh
DEPLOYDIR=$(pwd)/deploy
readonly DEPLOYDIR
readonly STATEDIR=$DEPLOYDIR/state
```
it would probably be something like:
```sh
DEPLOYDIR=${DEPLOYDIR:-$(pwd)/deploy}
readonly DEPLOYDIR
readonly STATEDIR=$DEPLOYDIR/state
```
But in all honesty... I can't remember the exact reason I opened this issue. So really we can probably just close this issue.

**Comment by gianarb** [comment]
> So really we can probably just close this issue.

I will take it for now! If something shows up feel free to open a new one or this one
