### ISSUE TITLE
Tinkerbell vision & mission

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#83]
Hi everyone, I wanted to know a bit more about the vision & mission for Tinkerbell.

I've just started an awesome bare-metal repo which lists Tinkerbell alongside some classic projects and products. There's also some writing and analysis I'm planning on doing in a very short period of time.

Could you help me with some of these questions? I don't mind taking them over email.

## What's the USP vs prior art?

What is / or are the USPs that Tinkerbell brings in the context of prior art? How does it compare to the incumbent projects and products? What are the main use-cases and pros/cons?

Are there certain things that are not in scope? I.e. IPMI Is there a story for that?

In what ways is Tinkerbell similar to the Packet API? What lessons were learned and then applied?

## Key concepts

Workflows seem to be important. What are the alternatives to a workflow?

## What was the reason that Tinkerbell was created?

Why was Tinkerbell created? Is it doing it in a different way? Is that a novel technique and why?

Who's the main sponsor for the project? Are other companies involved or coming on board to contribute / test / build it?

## Community / ethos / vision

What is the ethos for the project? I see that Go, gRPC is used and docker-compose. Are there values or experiences that lead to these choices?

If there was a new developer that wanted to contribute, what values or decisions could be codified and written up to help them make a meaningful contribution?

What would the ideal community look like, 6 months from now? Is there a GA / 1.0 release on the horizon?

Thanks a lot 👍 

Alex

**Comment by mrmrcoleman** [comment]
Hey @alexellis thanks for including us in the Awesome Bare Metal repo and my apologies for the long delay on getting an answer to this issue. There are internal conversations happening to start sharing more of the "big picture" with the community and once they are ready to share we'll be announcing them in the community slack. That work is tracked internally, so I'm closing this issue.
