### ISSUE TITLE
tink-worker for arm64

### ISSUE THREAD

**Issue by Ottovsky** [tinkerbell/tink#86]
Hey there,

Currently there is no valid build of tink-worker for arm64, so any execution on for example raspberry pi is failing:
```
pi@raspberrypi:~ $ docker run -ti --entrypoint /bin/sh quay.io/tinkerbell/tink-worker
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size
```
It would be nice, if you could have multi architecture images stored in your registry.

**Comment by mrmrcoleman** [comment]
Hey @Ottovsky I believe you did some work to get Tink working for arm64 already? If so could you share your work here please?

**Comment by Ottovsky** [comment]
Hey,

I actually just compiled it for the `armv7` and build docker image using the existing Dockerfile:
```
GOARCH=arm GOOS=linux GOARM_VERSION=7 CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o tink-worker worker/*.go
```
It would be nice to do tink-worker releases for different cpu architecture.

**Comment by mmlb** [comment]
@Ottovsky, now that https://github.com/tinkerbell/tink/pull/419 landed you can compile the tink-worker binary either with `make crosscompile` or for your exact case:
```
make cmd/tink-worker/tink-worker-linux-armv7
GOOS=linux GOARCH=arm GOARM=7 go build -ldflags "-X main.version=d9d9077" -o cmd/tink-worker/tink-worker-linux-armv7 ./cmd/tink-worker
```
