### ISSUE TITLE
Insecure defaults from the setup instructions

### ISSUE THREAD

**Issue by alexellis** [tinkerbell/tink#90]
After following the [setup instructions](https://tinkerbell.org/setup), all services appear to be directly exposed on the Internet which is never a good idea, Kibana for instance has no authentication or TLS configured.

<img width="2123" alt="Screenshot 2020-04-30 at 16 48 38" src="https://user-images.githubusercontent.com/6358735/80731175-75286b00-8b02-11ea-9b64-eb0c42d2cffb.png">

Please consider removing this default in favour of accessing the dashboards via SSH tunnels or by [using inlets](https://inlets.dev).

Do the nodes even need a public IP? I hear that Packet now supports nodes with no public IPs, perhaps the terraform could provision a tiny Type0 to run Nginx as a reverse proxy with auth?

These are the ports that are open:

<img width="2339" alt="Screenshot 2020-04-30 at 16 50 02" src="https://user-images.githubusercontent.com/6358735/80731318-a7d26380-8b02-11ea-8e0f-b648ca978f78.png">

I do not consider this to be a security advisory that needs to be handled via backchannels or email, this is probably just an oversight. If the team feel otherwise I can remove the issue.

**Comment by nathangoulding** [comment]
Agreed. Can we collect some suggestions / thoughts? 

- The terraform script we provide for packet demo could set some basic iptables rules if it detects a public interface. It could also accept a flag or parameter to disable that default behavior. 

- We add a warning for those running the setup script manually, with some sane defaults. 

Thoughts?

**Comment by alexellis** [comment]
Hi Nathan,

Glad that this resonates. My suggestions are in the original issue:

* 1) Use private Packet hosts only without any public IPs, with one Type0 added in which will act as a gateway running a reverse proxy Nginx would suit this task well and is easy to automate
* 2) Configuration as above, but with users accessing the hosts over ssh tunnels via a jump box, with nothing exposed publicly. `ssh -L 5601:provisioner-ip:5601 root@jump-host` then access via localhost:5601
* 3) Above configuration using [inlets](https://inlets.dev) instead of SSH, punching out to an existing Packet host as a jump box.

I also think your idea about adding IP tables rules to prevent access to all of the above sounds good in principle. In practice Docker interferes with iptables and makes it impractical to achieve that result.

**Comment by alexellis** [comment]
Example of inlets with HTTPS provided by Caddy, Caddy has an open usage license now can also decorate endpoints with basic auth as required for things like Kibana. https://blog.alexellis.io/https-inlets-local-endpoints/

**Comment by mrmrcoleman** [comment]
First step is to add a warning on the website explaining that this is an insecure example while we're investigating an actual fix.

**Comment by alexellis** [comment]
@gianarb I saw you closed the other script relating to ports. I think this one needs addressing rather than closing. Hopefully I can pre-empt you there.

**Comment by gianarb** [comment]
This issue is ALWAYS in my mind! Yep we started something here #232 .

I kind of thing the same concept I tried to describe there applies here and Kibana is not even part of the stack anymore.
